# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l0_path 0
scoreboard players set @s ml_l0tza 1
scoreboard players set @s ml_l0tzt 0
scoreboard players operation @s ml_l0tzd = @s ml_lc_d
scoreboard players operation @s ml_l0tze = @s ml_le_easing
scoreboard players operation @s ml_l0tzf = @s ml_lc_f
scoreboard players operation @s ml_l0tzz = @s ml_lc_z
scoreboard players operation @s ml_l0tzv = @s ml_lc_f
execute if score @s ml_l0tzd matches 0 run function monolith_anim:layer/slot/0/tz/finish
function monolith_anim:layer/slot/0/refresh
