# Generated by tools/build-animation-nodes.mjs
execute unless entity @s[tag=monolith_anim.node] run return 0
execute unless score #selected ml_n_id matches 1.. run return 0
execute if score @s ml_n_id = #selected ml_n_id run return 0
scoreboard players set @s ml_nc_mode -1
scoreboard players set @s ml_nc_eye -1
$function monolith_anim:parent/mode/$(mode)
$function monolith_anim:parent/anchor/$(anchor)
execute unless score @s ml_nc_mode matches 0..2 run return 0
execute unless score @s ml_nc_eye matches 0..1 run return 0
scoreboard players operation #bind_id ml_n_math = @s ml_n_id
scoreboard players set #cycle ml_n_math 0
scoreboard players set #steps ml_n_math 0
scoreboard players set #found ml_n_math 0
execute store result storage monolith_anim:node_args id int 1 run scoreboard players get #selected ml_n_id
function monolith_anim:parent/check with storage monolith_anim:node_args
execute unless score #found ml_n_math matches 1 run return 0
execute if score #cycle ml_n_math matches 1 run return 0
execute if score #is_node ml_n_math matches 1 if score @s ml_nc_mode matches 1 run return 0
execute if score #is_node ml_n_math matches 1 if score @s ml_nc_eye matches 1 run return 0
function monolith_anim:parent/check_descendants
execute if score #cycle ml_n_math matches 1 run return 0
scoreboard players operation @s ml_n_parent = #selected ml_n_id
scoreboard players operation @s ml_n_mode = @s ml_nc_mode
scoreboard players operation @s ml_n_eye = @s ml_nc_eye
return 1
