# Generated by tools/build-animation-nodes.mjs
$execute as @e[tag=monolith_anim.node,scores={ml_n_id=$(id)},limit=1] run function monolith_anim:parent/check_node
$execute if entity @e[tag=monolith_anim.anchor,scores={ml_n_id=$(id)},limit=1] run scoreboard players set #found ml_n_math 1
$execute if entity @e[tag=monolith_anim.anchor,scores={ml_n_id=$(id)},limit=1] run scoreboard players set #is_node ml_n_math 0
