# Generated by tools/build-animation-nodes.mjs
execute if score #steps ml_n_math matches 9.. run scoreboard players set #cycle ml_n_math 1
execute if score #cycle ml_n_math matches 1 run return 0
execute store result storage monolith_anim:node_args id int 1 run scoreboard players get @s ml_n_id
scoreboard players add #steps ml_n_math 1
function monolith_anim:parent/check_children with storage monolith_anim:node_args
scoreboard players remove #steps ml_n_math 1
