# Generated by tools/build-animation-nodes.mjs
scoreboard players set #found ml_n_math 1
execute if score @s ml_n_id = #bind_id ml_n_math run scoreboard players set #cycle ml_n_math 1
scoreboard players add #steps ml_n_math 1
execute if score #steps ml_n_math matches 9.. run scoreboard players set #cycle ml_n_math 1
execute if score #cycle ml_n_math matches 1 run return 0
execute store result storage monolith_anim:node_args id int 1 run scoreboard players get @s ml_n_parent
execute if score @s ml_n_parent matches 1.. run function monolith_anim:parent/check with storage monolith_anim:node_args
scoreboard players set #is_node ml_n_math 1
