# Generated by tools/build-animation-nodes.mjs
scoreboard players set #selected ml_n_id 0
function monolith_anim:node/identity
execute unless score @s ml_n_id matches 1.. run return 0
execute unless entity @s[tag=monolith_anim.node] run tag @s add monolith_anim.anchor
scoreboard players operation #selected ml_n_id = @s ml_n_id
return 1
