# Generated by tools/build-animation-nodes.mjs
# Bake world orientation as a quaternion offset; preserve current position and ongoing local animation.
execute unless entity @s[tag=monolith_anim.node] run return 0
execute unless score @s ml_n_ready matches 1 run return 0
scoreboard players operation @s ml_n_ox = @s ml_n_wx
scoreboard players operation @s ml_n_oy = @s ml_n_wy
scoreboard players operation @s ml_n_oz = @s ml_n_wz
scoreboard players operation @s ml_n_ox -= @s ml_n_vx
scoreboard players operation @s ml_n_oy -= @s ml_n_vy
scoreboard players operation @s ml_n_oz -= @s ml_n_vz
scoreboard players operation @s ml_n_ux = @s ml_n_px
scoreboard players operation @s ml_n_uy = @s ml_n_py
scoreboard players operation @s ml_n_uz = @s ml_n_pz
scoreboard players operation @s ml_n_uw = @s ml_n_pw
scoreboard players set @s ml_n_unbound 1
scoreboard players set @s ml_n_parent 0
return 1
