# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players operation @s ml_l3tyv = @s ml_l3tyz
scoreboard players set @s ml_l3tya 0
function monolith_anim:layer/slot/3/refresh
