# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l3_path 0
scoreboard players set @s ml_l3tya 1
scoreboard players set @s ml_l3tyt 0
scoreboard players operation @s ml_l3tyd = @s ml_lc_d
scoreboard players operation @s ml_l3tye = @s ml_le_easing
scoreboard players operation @s ml_l3tyf = @s ml_lc_f
scoreboard players operation @s ml_l3tyz = @s ml_lc_z
scoreboard players operation @s ml_l3tyv = @s ml_lc_f
execute if score @s ml_l3tyd matches 0 run function monolith_anim:layer/slot/3/ty/finish
function monolith_anim:layer/slot/3/refresh
