# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players add @s ml_l3tyt 1
execute if score @s ml_l3tyt >= @s ml_l3tyd run return run function monolith_anim:layer/slot/3/ty/finish
scoreboard players operation @s ml_le_tmp0 = @s ml_l3tyt
scoreboard players operation @s ml_le_tmp0 *= #scale ml_le_tmp0
scoreboard players operation @s ml_le_tmp0 /= @s ml_l3tyd
scoreboard players operation @s ml_le_easing = @s ml_l3tye
function monolith_anim:easing/dispatch
scoreboard players operation @s ml_lm_u = @s ml_le_tmp1
scoreboard players operation @s ml_lm_a = @s ml_l3tyf
scoreboard players operation @s ml_lm_b = @s ml_l3tyz
function monolith_anim:math/layer_lerp
scoreboard players operation @s ml_l3tyv = @s ml_lm_v
