# Generated by tools/build-transform.mjs
scoreboard players operation @s ml_rot_i = @s ml_a_value
scoreboard players operation @s ml_rot_i %= #turn ml_a_tmp0
scoreboard players operation @s ml_rot_rem = @s ml_rot_i
scoreboard players operation @s ml_rot_rem %= #degree ml_a_tmp0
scoreboard players operation @s ml_rot_i /= #degree ml_a_tmp0
scoreboard players operation @s ml_rot_j = @s ml_rot_i
scoreboard players add @s ml_rot_j 1
execute store result storage monolith:rotation_args i int 1 run scoreboard players get @s ml_rot_i
execute store result storage monolith:rotation_args j int 1 run scoreboard players get @s ml_rot_j
function monolith:animation/rotation/read with storage monolith:rotation_args
scoreboard players operation @s ml_rot_s1 -= @s ml_rot_s0
scoreboard players operation @s ml_rot_s1 *= @s ml_rot_rem
scoreboard players operation @s ml_rot_s1 /= #degree ml_a_tmp0
scoreboard players operation @s ml_rot_s0 += @s ml_rot_s1
scoreboard players operation @s ml_rot_c1 -= @s ml_rot_c0
scoreboard players operation @s ml_rot_c1 *= @s ml_rot_rem
scoreboard players operation @s ml_rot_c1 /= #degree ml_a_tmp0
scoreboard players operation @s ml_rot_c0 += @s ml_rot_c1
