# Generated by tools/build-transform.mjs
$execute store result score @s ml_rot_s0 run data get storage monolith:rotation_lut values[$(i)].s 1
$execute store result score @s ml_rot_s1 run data get storage monolith:rotation_lut values[$(j)].s 1
$execute store result score @s ml_rot_c0 run data get storage monolith:rotation_lut values[$(i)].c 1
$execute store result score @s ml_rot_c1 run data get storage monolith:rotation_lut values[$(j)].c 1
