# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l0sza 1
scoreboard players set @s ml_l0szt 0
scoreboard players operation @s ml_l0szd = @s ml_lc_d
scoreboard players operation @s ml_l0sze = @s ml_le_easing
scoreboard players operation @s ml_l0szf = @s ml_lc_f
scoreboard players operation @s ml_l0szz = @s ml_lc_z
scoreboard players operation @s ml_l0szv = @s ml_lc_f
execute if score @s ml_l0szd matches 0 run function monolith_anim:layer/slot/0/sz/finish
function monolith_anim:layer/slot/0/refresh
