# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players add @s ml_l0szt 1
execute if score @s ml_l0szt >= @s ml_l0szd run return run function monolith_anim:layer/slot/0/sz/finish
scoreboard players operation @s ml_le_tmp0 = @s ml_l0szt
scoreboard players operation @s ml_le_tmp0 *= #scale ml_le_tmp0
scoreboard players operation @s ml_le_tmp0 /= @s ml_l0szd
scoreboard players operation @s ml_le_easing = @s ml_l0sze
function monolith_anim:easing/dispatch
scoreboard players operation @s ml_lm_u = @s ml_le_tmp1
scoreboard players operation @s ml_lm_a = @s ml_l0szf
scoreboard players operation @s ml_lm_b = @s ml_l0szz
function monolith_anim:math/layer_lerp
scoreboard players operation @s ml_l0szv = @s ml_lm_v
