# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players operation @s ml_l3txv = @s ml_l3txz
scoreboard players set @s ml_l3txa 0
function monolith_anim:layer/slot/3/refresh
