# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l3_path 0
scoreboard players set @s ml_l3txa 1
scoreboard players set @s ml_l3txt 0
scoreboard players operation @s ml_l3txd = @s ml_lc_d
scoreboard players operation @s ml_l3txe = @s ml_le_easing
scoreboard players operation @s ml_l3txf = @s ml_lc_f
scoreboard players operation @s ml_l3txz = @s ml_lc_z
scoreboard players operation @s ml_l3txv = @s ml_lc_f
execute if score @s ml_l3txd matches 0 run function monolith_anim:layer/slot/3/tx/finish
function monolith_anim:layer/slot/3/refresh
