# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players add @s ml_l3txt 1
execute if score @s ml_l3txt >= @s ml_l3txd run return run function monolith_anim:layer/slot/3/tx/finish
scoreboard players operation @s ml_le_tmp0 = @s ml_l3txt
scoreboard players operation @s ml_le_tmp0 *= #scale ml_le_tmp0
scoreboard players operation @s ml_le_tmp0 /= @s ml_l3txd
scoreboard players operation @s ml_le_easing = @s ml_l3txe
function monolith_anim:easing/dispatch
scoreboard players operation @s ml_lm_u = @s ml_le_tmp1
scoreboard players operation @s ml_lm_a = @s ml_l3txf
scoreboard players operation @s ml_lm_b = @s ml_l3txz
function monolith_anim:math/layer_lerp
scoreboard players operation @s ml_l3txv = @s ml_lm_v
