# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l3rza 1
scoreboard players set @s ml_l3rzt 0
scoreboard players operation @s ml_l3rzd = @s ml_lc_d
scoreboard players operation @s ml_l3rze = @s ml_le_easing
scoreboard players operation @s ml_l3rzf = @s ml_lc_f
scoreboard players operation @s ml_l3rzz = @s ml_lc_z
scoreboard players operation @s ml_l3rzv = @s ml_lc_f
execute if score @s ml_l3rzd matches 0 run function monolith_anim:layer/slot/3/rz/finish
function monolith_anim:layer/slot/3/refresh
