# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players add @s ml_l3rzt 1
execute if score @s ml_l3rzt >= @s ml_l3rzd run return run function monolith_anim:layer/slot/3/rz/finish
scoreboard players operation @s ml_le_tmp0 = @s ml_l3rzt
scoreboard players operation @s ml_le_tmp0 *= #scale ml_le_tmp0
scoreboard players operation @s ml_le_tmp0 /= @s ml_l3rzd
scoreboard players operation @s ml_le_easing = @s ml_l3rze
function monolith_anim:easing/dispatch
scoreboard players operation @s ml_lm_u = @s ml_le_tmp1
scoreboard players operation @s ml_lm_a = @s ml_l3rzf
scoreboard players operation @s ml_lm_b = @s ml_l3rzz
function monolith_anim:math/layer_lerp
scoreboard players operation @s ml_l3rzv = @s ml_lm_v
