# Generated by tools/build-transform.mjs
scoreboard players set @s ml_t_active 0
scoreboard players set @s ml_r_active 0
scoreboard players set @s ml_s_active 0
scoreboard players set @s ml_a_elapsed 0
scoreboard players set @s ml_a_duration 0
tag @s remove monolith.animating
