# Generated by tools/build-transform.mjs
execute if score @s ml_t_active matches 1 run function monolith:animation/track/t/finish
execute if score @s ml_r_active matches 1 run function monolith:animation/track/r/finish
execute if score @s ml_s_active matches 1 run function monolith:animation/track/s/finish
function monolith:animation/track/refresh
