# Generated by tools/build-transform.mjs
# Backward-compatible scalar API; overwrite only the selected transform track.
execute unless entity @s[type=minecraft:block_display] unless entity @s[type=minecraft:item_display] unless entity @s[type=minecraft:text_display] run return 0
scoreboard players set @s ml_a_property -1
scoreboard players set @s ml_a_easing -1
$function monolith:animation/adapter/resolve/$(property)
$function monolith:animation/easing/resolve/$(easing)
execute unless score @s ml_a_property matches 0..12 run return 0
execute if score @s ml_a_property matches 9 run return 0
execute unless score @s ml_a_easing matches 0..30 run return 0
execute if entity @s[tag=monolith.child] if score @s ml_a_property matches 7 run scoreboard players set @s ml_a_property 11
execute if entity @s[tag=monolith.child] if score @s ml_a_property matches 8 run scoreboard players set @s ml_a_property 10
$scoreboard players set @s ml_a_from $(from)
$scoreboard players set @s ml_a_to $(to)
$scoreboard players set @s ml_a_duration $(duration)
# Documented range prevents scoreboard intermediate overflow.
execute unless score @s ml_a_from matches -1000000..1000000 run return 0
execute unless score @s ml_a_to matches -1000000..1000000 run return 0
execute if score @s ml_a_duration matches 200001.. run return 0
scoreboard players set @s ml_a_elapsed 0
execute if score @s ml_a_property matches 0..2 run scoreboard players set @s ml_space 0
execute if score @s ml_a_property matches 0..2 run function monolith:animation/track/t/start
execute if score @s ml_a_property matches 3..6 run function monolith:animation/track/s/start
execute if score @s ml_a_property matches 7..8 run function monolith:animation/track/r/start
execute if score @s ml_a_property matches 10..12 run function monolith:animation/track/r/start
