# Generated by tools/build-transform.mjs
execute as @e[tag=monolith.debug.boss] at @s run function monolith:animation/debug/boss_tick
execute as @e[tag=monolith.animating,tag=!monolith.child] run function monolith:animation/update
function monolith:animation/parent/tick
execute as @e[tag=monolith.animating,tag=monolith.child] run function monolith:animation/update
execute as @e[tag=monolith.showcase] at @s run function monolith:animation/debug/showcase_tick
