# Generated by tools/build-transform.mjs
# A missing/unloaded parent freezes all tracks; resume when the same parent returns.
execute if entity @s[tag=monolith.child] unless score @s ml_parent_seen matches 1 run return 0
execute if score @s ml_t_active matches 1 run function monolith:animation/track/t/update
execute if score @s ml_r_active matches 1 run function monolith:animation/track/r/update
execute if score @s ml_s_active matches 1 run function monolith:animation/track/s/update
function monolith:animation/track/refresh
data modify entity @s start_interpolation set value 0
