# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players operation @s ml_l0sxv = @s ml_l0sxz
scoreboard players set @s ml_l0sxa 0
function monolith_anim:layer/slot/0/refresh
