# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l0sxa 1
scoreboard players set @s ml_l0sxt 0
scoreboard players operation @s ml_l0sxd = @s ml_lc_d
scoreboard players operation @s ml_l0sxe = @s ml_le_easing
scoreboard players operation @s ml_l0sxf = @s ml_lc_f
scoreboard players operation @s ml_l0sxz = @s ml_lc_z
scoreboard players operation @s ml_l0sxv = @s ml_lc_f
execute if score @s ml_l0sxd matches 0 run function monolith_anim:layer/slot/0/sx/finish
function monolith_anim:layer/slot/0/refresh
