# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players add @s ml_l0sxt 1
execute if score @s ml_l0sxt >= @s ml_l0sxd run return run function monolith_anim:layer/slot/0/sx/finish
scoreboard players operation @s ml_le_tmp0 = @s ml_l0sxt
scoreboard players operation @s ml_le_tmp0 *= #scale ml_le_tmp0
scoreboard players operation @s ml_le_tmp0 /= @s ml_l0sxd
scoreboard players operation @s ml_le_easing = @s ml_l0sxe
function monolith_anim:easing/dispatch
scoreboard players operation @s ml_lm_u = @s ml_le_tmp1
scoreboard players operation @s ml_lm_a = @s ml_l0sxf
scoreboard players operation @s ml_lm_b = @s ml_l0sxz
function monolith_anim:math/layer_lerp
scoreboard players operation @s ml_l0sxv = @s ml_lm_v
