# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players operation @s ml_l2szv = @s ml_l2szz
scoreboard players set @s ml_l2sza 0
function monolith_anim:layer/slot/2/refresh
