# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l2sza 1
scoreboard players set @s ml_l2szt 0
scoreboard players operation @s ml_l2szd = @s ml_lc_d
scoreboard players operation @s ml_l2sze = @s ml_le_easing
scoreboard players operation @s ml_l2szf = @s ml_lc_f
scoreboard players operation @s ml_l2szz = @s ml_lc_z
scoreboard players operation @s ml_l2szv = @s ml_lc_f
execute if score @s ml_l2szd matches 0 run function monolith_anim:layer/slot/2/sz/finish
function monolith_anim:layer/slot/2/refresh
