# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players add @s ml_l2szt 1
execute if score @s ml_l2szt >= @s ml_l2szd run return run function monolith_anim:layer/slot/2/sz/finish
scoreboard players operation @s ml_le_tmp0 = @s ml_l2szt
scoreboard players operation @s ml_le_tmp0 *= #scale ml_le_tmp0
scoreboard players operation @s ml_le_tmp0 /= @s ml_l2szd
scoreboard players operation @s ml_le_easing = @s ml_l2sze
function monolith_anim:easing/dispatch
scoreboard players operation @s ml_lm_u = @s ml_le_tmp1
scoreboard players operation @s ml_lm_a = @s ml_l2szf
scoreboard players operation @s ml_lm_b = @s ml_l2szz
function monolith_anim:math/layer_lerp
scoreboard players operation @s ml_l2szv = @s ml_lm_v
