# Generated by tools/build-animation-debug.mjs
execute if score @s ml_seq_time matches 0 run function monolith_anim:layer/start {slot:0,property:"scale_xyz",from:100,to:1000,duration:20,easing:"out_back"}
