# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players operation @s ml_l1sxv = @s ml_l1sxz
scoreboard players set @s ml_l1sxa 0
function monolith_anim:layer/slot/1/refresh
