# Generated by tools/build-animation-nodes.mjs
data merge entity @s {Rotation:[0f,0f],interpolation_duration:1,start_interpolation:0,teleport_duration:1,billboard:"fixed"}
data modify entity @s transformation.translation set value [0f,0f,0f]
data modify entity @s transformation.right_rotation set value [0f,0f,0f,1f]
execute store result entity @s transformation.left_rotation[0] float 0.0001 run scoreboard players get @s ml_n_qx
execute store result entity @s transformation.left_rotation[1] float 0.0001 run scoreboard players get @s ml_n_qy
execute store result entity @s transformation.left_rotation[2] float 0.0001 run scoreboard players get @s ml_n_qz
execute store result entity @s transformation.left_rotation[3] float 0.0001 run scoreboard players get @s ml_n_qw
execute store result entity @s transformation.scale[0] float 0.001 run scoreboard players get @s ml_n_scalex
execute store result entity @s transformation.scale[1] float 0.001 run scoreboard players get @s ml_n_scaley
execute store result entity @s transformation.scale[2] float 0.001 run scoreboard players get @s ml_n_scalez
