# Generated by tools/build-animation-nodes.mjs
execute unless entity @s[tag=monolith_anim.node] run return 0
$scoreboard players set @s ml_nc_tx $(tx)
$scoreboard players set @s ml_nc_ty $(ty)
$scoreboard players set @s ml_nc_tz $(tz)
$scoreboard players set @s ml_nc_rx $(rx)
$scoreboard players set @s ml_nc_ry $(ry)
$scoreboard players set @s ml_nc_rz $(rz)
$scoreboard players set @s ml_nc_sx $(sx)
$scoreboard players set @s ml_nc_sy $(sy)
$scoreboard players set @s ml_nc_sz $(sz)
execute unless score @s ml_nc_tx matches -1000000..1000000 run return 0
execute unless score @s ml_nc_rx matches -3600000..3600000 run return 0
execute unless score @s ml_nc_sx matches -8000..8000 run return 0
execute unless score @s ml_nc_ty matches -1000000..1000000 run return 0
execute unless score @s ml_nc_ry matches -3600000..3600000 run return 0
execute unless score @s ml_nc_sy matches -8000..8000 run return 0
execute unless score @s ml_nc_tz matches -1000000..1000000 run return 0
execute unless score @s ml_nc_rz matches -3600000..3600000 run return 0
execute unless score @s ml_nc_sz matches -8000..8000 run return 0
scoreboard players operation @s ml_n_basex = @s ml_nc_tx
scoreboard players operation @s ml_n_rx = @s ml_nc_rx
scoreboard players operation @s ml_n_sx = @s ml_nc_sx
scoreboard players operation @s ml_n_basey = @s ml_nc_ty
scoreboard players operation @s ml_n_ry = @s ml_nc_ry
scoreboard players operation @s ml_n_sy = @s ml_nc_sy
scoreboard players operation @s ml_n_basez = @s ml_nc_tz
scoreboard players operation @s ml_n_rz = @s ml_nc_rz
scoreboard players operation @s ml_n_sz = @s ml_nc_sz
return 1
