# Generated by tools/build-animation-nodes.mjs
scoreboard players operation #px ml_n_math = @s ml_n_wx
scoreboard players operation #py ml_n_math = @s ml_n_wy
scoreboard players operation #pz ml_n_math = @s ml_n_wz
scoreboard players operation #qx ml_n_math = @s ml_n_qx
scoreboard players operation #qy ml_n_math = @s ml_n_qy
scoreboard players operation #qz ml_n_math = @s ml_n_qz
scoreboard players operation #qw ml_n_math = @s ml_n_qw
scoreboard players operation #depth ml_n_math = @s ml_n_depth
execute store result storage monolith_anim:node_args id int 1 run scoreboard players get @s ml_n_id
function monolith_anim:node/children_selected with storage monolith_anim:node_args
