# Generated by tools/build-animation-nodes.mjs
scoreboard players set @s ml_n_pdirty 0
scoreboard players set @s ml_n_rdirty 0
scoreboard players set @s ml_n_vdirty 0
scoreboard players set @s ml_n_dirty 0
execute unless score @s ml_n_px = #qx ml_n_math run scoreboard players set @s ml_n_pdirty 1
execute unless score @s ml_n_py = #qy ml_n_math run scoreboard players set @s ml_n_pdirty 1
execute unless score @s ml_n_pz = #qz ml_n_math run scoreboard players set @s ml_n_pdirty 1
execute unless score @s ml_n_pw = #qw ml_n_math run scoreboard players set @s ml_n_pdirty 1
scoreboard players operation @s ml_n_px = #qx ml_n_math
scoreboard players operation @s ml_n_py = #qy ml_n_math
scoreboard players operation @s ml_n_pz = #qz ml_n_math
scoreboard players operation @s ml_n_pw = #qw ml_n_math
execute if score @s ml_n_mode matches 0 run scoreboard players set @s ml_n_px 0
execute if score @s ml_n_mode matches 0 run scoreboard players set @s ml_n_py 0
execute if score @s ml_n_mode matches 0 run scoreboard players set @s ml_n_pz 0
execute if score @s ml_n_mode matches 0 run scoreboard players set @s ml_n_pw 10000
scoreboard players operation @s ml_n_depth = #depth ml_n_math
scoreboard players add @s ml_n_depth 1
function monolith_anim:layer/tick
scoreboard players operation @s ml_n_tx = @s ml_n_basex
scoreboard players operation @s ml_n_tx += @s ml_l_tx
scoreboard players operation @s ml_n_ex = @s ml_n_rx
scoreboard players operation @s ml_n_ex += @s ml_l_rx
scoreboard players operation @s ml_n_ty = @s ml_n_basey
scoreboard players operation @s ml_n_ty += @s ml_l_ty
scoreboard players operation @s ml_n_ey = @s ml_n_ry
scoreboard players operation @s ml_n_ey += @s ml_l_ry
scoreboard players operation @s ml_n_tz = @s ml_n_basez
scoreboard players operation @s ml_n_tz += @s ml_l_tz
scoreboard players operation @s ml_n_ez = @s ml_n_rz
scoreboard players operation @s ml_n_ez += @s ml_l_rz
execute unless score @s ml_n_ex = @s ml_n_oldrx run scoreboard players set @s ml_n_rdirty 1
execute unless score @s ml_n_ey = @s ml_n_oldry run scoreboard players set @s ml_n_rdirty 1
execute unless score @s ml_n_ez = @s ml_n_oldrz run scoreboard players set @s ml_n_rdirty 1
execute unless score @s ml_n_tx = @s ml_n_oldtx run scoreboard players set @s ml_n_vdirty 1
execute unless score @s ml_n_ty = @s ml_n_oldty run scoreboard players set @s ml_n_vdirty 1
execute unless score @s ml_n_tz = @s ml_n_oldtz run scoreboard players set @s ml_n_vdirty 1
execute if score @s ml_n_pdirty matches 1 run scoreboard players set @s ml_n_vdirty 1
execute if score @s ml_n_vdirty matches 1 run function monolith_anim:node/update_vector
scoreboard players operation @s ml_n_oldwx = @s ml_n_wx
scoreboard players operation @s ml_n_oldwy = @s ml_n_wy
scoreboard players operation @s ml_n_oldwz = @s ml_n_wz
scoreboard players operation @s ml_n_wx = @s ml_n_vx
scoreboard players operation @s ml_n_wx += #px ml_n_math
scoreboard players operation @s ml_n_wy = @s ml_n_vy
scoreboard players operation @s ml_n_wy += #py ml_n_math
scoreboard players operation @s ml_n_wz = @s ml_n_vz
scoreboard players operation @s ml_n_wz += #pz ml_n_math
execute unless score @s ml_n_wx = @s ml_n_oldwx run scoreboard players set @s ml_n_dirty 1
execute unless score @s ml_n_wy = @s ml_n_oldwy run scoreboard players set @s ml_n_dirty 1
execute unless score @s ml_n_wz = @s ml_n_oldwz run scoreboard players set @s ml_n_dirty 1
execute if score @s ml_n_rdirty matches 1 run function monolith_anim:node/update_rotation
execute if score @s ml_n_rdirty matches 1 run scoreboard players set @s ml_n_pdirty 1
execute if score @s ml_n_pdirty matches 1 run function monolith_anim:node/update_world_rotation
scoreboard players operation @s ml_n_qx = @s ml_n_wqx
scoreboard players operation @s ml_n_qy = @s ml_n_wqy
scoreboard players operation @s ml_n_qz = @s ml_n_wqz
scoreboard players operation @s ml_n_qw = @s ml_n_wqw
scoreboard players operation @s ml_n_oldsx = @s ml_n_scalex
scoreboard players operation @s ml_n_oldsy = @s ml_n_scaley
scoreboard players operation @s ml_n_oldsz = @s ml_n_scalez
scoreboard players operation @s ml_n_scalex = @s ml_n_sx
scoreboard players operation @s ml_n_scalex *= @s ml_l_sx
scoreboard players operation @s ml_n_scalex /= #degree ml_n_math
scoreboard players operation @s ml_n_scaley = @s ml_n_sy
scoreboard players operation @s ml_n_scaley *= @s ml_l_sy
scoreboard players operation @s ml_n_scaley /= #degree ml_n_math
scoreboard players operation @s ml_n_scalez = @s ml_n_sz
scoreboard players operation @s ml_n_scalez *= @s ml_l_sz
scoreboard players operation @s ml_n_scalez /= #degree ml_n_math
execute unless score @s ml_n_scalex = @s ml_n_oldsx run scoreboard players set @s ml_n_dirty 1
execute unless score @s ml_n_scaley = @s ml_n_oldsy run scoreboard players set @s ml_n_dirty 1
execute unless score @s ml_n_scalez = @s ml_n_oldsz run scoreboard players set @s ml_n_dirty 1
execute if score @s ml_n_dirty matches 1 store result entity @s Pos[0] double 0.001 run scoreboard players get @s ml_n_wx
execute if score @s ml_n_dirty matches 1 store result entity @s Pos[1] double 0.001 run scoreboard players get @s ml_n_wy
execute if score @s ml_n_dirty matches 1 store result entity @s Pos[2] double 0.001 run scoreboard players get @s ml_n_wz
execute if score @s ml_n_external matches 1 store result entity @s Pos[0] double 0.001 run scoreboard players get @s ml_n_wx
execute if score @s ml_n_external matches 1 store result entity @s Pos[1] double 0.001 run scoreboard players get @s ml_n_wy
execute if score @s ml_n_external matches 1 store result entity @s Pos[2] double 0.001 run scoreboard players get @s ml_n_wz
execute if score @s ml_n_dirty matches 1 unless entity @s[type=minecraft:marker] run function monolith_anim:node/apply_display
scoreboard players set @s ml_n_ready 1
