# Generated by tools/build-animation-nodes.mjs
$execute as @e[tag=monolith_anim.anchor,scores={ml_n_id=$(id)},limit=1] at @s run function monolith_anim:node/read_anchor {child:$(child),mode:$(mode),eye:$(eye)}
