# Generated by tools/build-animation-nodes.mjs
execute store result storage monolith_anim:node_args id int 1 run scoreboard players get @s ml_n_parent
execute store result storage monolith_anim:node_args child int 1 run scoreboard players get @s ml_n_id
execute store result storage monolith_anim:node_args mode int 1 run scoreboard players get @s ml_n_mode
execute store result storage monolith_anim:node_args eye int 1 run scoreboard players get @s ml_n_eye
scoreboard players set #found ml_n_math 0
function monolith_anim:node/external_selected with storage monolith_anim:node_args
execute unless score #found ml_n_math matches 1 run return 0
scoreboard players set @s ml_n_external 1
execute store result score #px ml_n_math run data get entity @s Pos[0] 1000
execute store result score #py ml_n_math run data get entity @s Pos[1] 1000
execute store result score #pz ml_n_math run data get entity @s Pos[2] 1000
scoreboard players set #depth ml_n_math -1
function monolith_anim:node/evaluate
