# Generated by tools/build-animation-nodes.mjs
execute if score @s ml_n_id matches 1.. run return 1
execute if score #next ml_n_id matches 2147483647 run return 0
scoreboard players add #next ml_n_id 1
scoreboard players operation @s ml_n_id = #next ml_n_id
return 1
