# Generated by tools/build-animation-nodes.mjs
execute if entity @s[tag=monolith_anim.node] run return 1
execute unless entity @s[type=minecraft:marker] unless entity @s[type=minecraft:block_display] unless entity @s[type=minecraft:item_display] unless entity @s[type=minecraft:text_display] run return 0
execute if entity @s[tag=monolith.child] run return 0
execute if entity @s[tag=monolith.parent] run return 0
execute if entity @s[tag=monolith.animating] run return 0
execute store result score @s ml_n_check run data get entity @s Pos[0] 1
execute unless score @s ml_n_check matches -1000000..1000000 run return 0
execute store result score @s ml_n_check run data get entity @s Pos[1] 1
execute unless score @s ml_n_check matches -1000000..1000000 run return 0
execute store result score @s ml_n_check run data get entity @s Pos[2] 1
execute unless score @s ml_n_check matches -1000000..1000000 run return 0
function monolith_anim:node/identity
execute unless score @s ml_n_id matches 1.. run return 0
tag @s add monolith_anim.node
tag @s remove monolith_anim.anchor
scoreboard players set @s ml_n_parent 0
scoreboard players set @s ml_n_mode 2
scoreboard players set @s ml_n_eye 0
scoreboard players set @s ml_n_ready 0
scoreboard players set @s ml_n_depth 0
scoreboard players set @s ml_n_unbound 0
execute store result score @s ml_n_ox run data get entity @s Pos[0] 1000
scoreboard players set @s ml_n_basex 0
scoreboard players set @s ml_n_rx 0
scoreboard players set @s ml_n_sx 1000
execute store result score @s ml_n_oy run data get entity @s Pos[1] 1000
scoreboard players set @s ml_n_basey 0
scoreboard players set @s ml_n_ry 0
scoreboard players set @s ml_n_sy 1000
execute store result score @s ml_n_oz run data get entity @s Pos[2] 1000
scoreboard players set @s ml_n_basez 0
scoreboard players set @s ml_n_rz 0
scoreboard players set @s ml_n_sz 1000
scoreboard players set @s ml_n_oldrx -2147483648
scoreboard players set @s ml_n_oldtx -2147483648
scoreboard players set @s ml_n_wx 0
scoreboard players set @s ml_n_scalex 0
scoreboard players set @s ml_n_oldry -2147483648
scoreboard players set @s ml_n_oldty -2147483648
scoreboard players set @s ml_n_wy 0
scoreboard players set @s ml_n_scaley 0
scoreboard players set @s ml_n_oldrz -2147483648
scoreboard players set @s ml_n_oldtz -2147483648
scoreboard players set @s ml_n_wz 0
scoreboard players set @s ml_n_scalez 0
scoreboard players set @s ml_n_px -99999
scoreboard players set @s ml_n_py -99999
scoreboard players set @s ml_n_pz -99999
scoreboard players set @s ml_n_pw -99999
execute store result score @s ml_n_rx run data get entity @s Rotation[1] 1000
execute store result score @s ml_n_ry run data get entity @s Rotation[0] -1000
function monolith_anim:layer/init
return 1
