# Generated by tools/build-animation-nodes.mjs
execute store result score @s ml_n_check run data get entity @s Pos[0] 1
execute unless score @s ml_n_check matches -1000000..1000000 run return 0
execute store result score @s ml_n_check run data get entity @s Pos[1] 1
execute unless score @s ml_n_check matches -1000000..1000000 run return 0
execute store result score @s ml_n_check run data get entity @s Pos[2] 1
execute unless score @s ml_n_check matches -1000000..1000000 run return 0
scoreboard players set @s ml_n_ex 0
scoreboard players set @s ml_n_ey 0
scoreboard players set @s ml_n_ez 0
$scoreboard players set @s ml_nc_mode $(mode)
$scoreboard players set @s ml_nc_eye $(eye)
execute if score @s ml_nc_mode matches 1.. store result score @s ml_n_ey run data get entity @s Rotation[0] -1000
execute if score @s ml_nc_mode matches 2 store result score @s ml_n_ex run data get entity @s Rotation[1] 1000
function monolith_anim:node/math/euler
scoreboard players operation #qx ml_n_math = @s ml_n_qx
scoreboard players operation #qy ml_n_math = @s ml_n_qy
scoreboard players operation #qz ml_n_math = @s ml_n_qz
scoreboard players operation #qw ml_n_math = @s ml_n_qw
$execute if score @s ml_nc_eye matches 0 run tp @e[tag=monolith_anim.node,scores={ml_n_id=$(child)},limit=1] ~ ~ ~
$execute if score @s ml_nc_eye matches 1 anchored eyes positioned ^ ^ ^ run tp @e[tag=monolith_anim.node,scores={ml_n_id=$(child)},limit=1] ~ ~ ~
scoreboard players set #found ml_n_math 1
