# Generated by tools/build-animation-nodes.mjs
tag @s remove monolith_anim.node
tag @s remove monolith_anim.anchor
function monolith_anim:layer/clear {slot:0}
function monolith_anim:layer/clear {slot:1}
function monolith_anim:layer/clear {slot:2}
function monolith_anim:layer/clear {slot:3}
return 1
