# Generated by tools/build-animation-nodes.mjs
scoreboard players set @s ml_n_external 0
scoreboard players operation #px ml_n_math = @s ml_n_ox
scoreboard players operation #py ml_n_math = @s ml_n_oy
scoreboard players operation #pz ml_n_math = @s ml_n_oz
scoreboard players set #qx ml_n_math 0
scoreboard players set #qy ml_n_math 0
scoreboard players set #qz ml_n_math 0
scoreboard players set #qw ml_n_math 10000
execute if score @s ml_n_unbound matches 1 run scoreboard players operation #qx ml_n_math = @s ml_n_ux
execute if score @s ml_n_unbound matches 1 run scoreboard players operation #qy ml_n_math = @s ml_n_uy
execute if score @s ml_n_unbound matches 1 run scoreboard players operation #qz ml_n_math = @s ml_n_uz
execute if score @s ml_n_unbound matches 1 run scoreboard players operation #qw ml_n_math = @s ml_n_uw
scoreboard players set #depth ml_n_math -1
function monolith_anim:node/evaluate
