# Generated by tools/build-animation-nodes.mjs
scoreboard players set @e[tag=monolith_anim.node] ml_n_ready 0
execute as @e[tag=monolith_anim.node,scores={ml_n_parent=0}] at @s run function monolith_anim:node/root
execute as @e[tag=monolith_anim.node,scores={ml_n_ready=0}] at @s run function monolith_anim:node/external
execute as @e[tag=monolith_anim.node,scores={ml_n_ready=1,ml_n_depth=0}] run function monolith_anim:node/children
execute as @e[tag=monolith_anim.node,scores={ml_n_ready=1,ml_n_depth=1}] run function monolith_anim:node/children
execute as @e[tag=monolith_anim.node,scores={ml_n_ready=1,ml_n_depth=2}] run function monolith_anim:node/children
execute as @e[tag=monolith_anim.node,scores={ml_n_ready=1,ml_n_depth=3}] run function monolith_anim:node/children
execute as @e[tag=monolith_anim.node,scores={ml_n_ready=1,ml_n_depth=4}] run function monolith_anim:node/children
execute as @e[tag=monolith_anim.node,scores={ml_n_ready=1,ml_n_depth=5}] run function monolith_anim:node/children
execute as @e[tag=monolith_anim.node,scores={ml_n_ready=1,ml_n_depth=6}] run function monolith_anim:node/children
execute as @e[tag=monolith_anim.node,scores={ml_n_ready=1,ml_n_depth=7}] run function monolith_anim:node/children
