# Generated by tools/build-animation-nodes.mjs
scoreboard players operation @s ml_n_qx = @s ml_n_px
scoreboard players operation @s ml_n_qy = @s ml_n_py
scoreboard players operation @s ml_n_qz = @s ml_n_pz
scoreboard players operation @s ml_n_qw = @s ml_n_pw
function monolith_anim:node/math/rotate
scoreboard players operation @s ml_n_oldtx = @s ml_n_tx
scoreboard players operation @s ml_n_oldty = @s ml_n_ty
scoreboard players operation @s ml_n_oldtz = @s ml_n_tz
