# Generated by tools/build-animation-nodes.mjs
scoreboard players operation @s ml_n_bx = @s ml_n_lqx
scoreboard players operation @s ml_n_ax = @s ml_n_px
scoreboard players operation @s ml_n_by = @s ml_n_lqy
scoreboard players operation @s ml_n_ay = @s ml_n_py
scoreboard players operation @s ml_n_bz = @s ml_n_lqz
scoreboard players operation @s ml_n_az = @s ml_n_pz
scoreboard players operation @s ml_n_bw = @s ml_n_lqw
scoreboard players operation @s ml_n_aw = @s ml_n_pw
function monolith_anim:node/math/multiply
function monolith_anim:node/math/normalize
scoreboard players operation @s ml_n_wqx = @s ml_n_qx
scoreboard players operation @s ml_n_wqy = @s ml_n_qy
scoreboard players operation @s ml_n_wqz = @s ml_n_qz
scoreboard players operation @s ml_n_wqw = @s ml_n_qw
scoreboard players set @s ml_n_dirty 1
