# Generated by tools/build-animation-nodes.mjs
function monolith_anim:node/math/euler
scoreboard players operation @s ml_n_lqx = @s ml_n_qx
scoreboard players operation @s ml_n_lqy = @s ml_n_qy
scoreboard players operation @s ml_n_lqz = @s ml_n_qz
scoreboard players operation @s ml_n_lqw = @s ml_n_qw
scoreboard players operation @s ml_n_oldrx = @s ml_n_ex
scoreboard players operation @s ml_n_oldry = @s ml_n_ey
scoreboard players operation @s ml_n_oldrz = @s ml_n_ez
