# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l1_path 0
scoreboard players set @s ml_l1tza 1
scoreboard players set @s ml_l1tzt 0
scoreboard players operation @s ml_l1tzd = @s ml_lc_d
scoreboard players operation @s ml_l1tze = @s ml_le_easing
scoreboard players operation @s ml_l1tzf = @s ml_lc_f
scoreboard players operation @s ml_l1tzz = @s ml_lc_z
scoreboard players operation @s ml_l1tzv = @s ml_lc_f
execute if score @s ml_l1tzd matches 0 run function monolith_anim:layer/slot/1/tz/finish
function monolith_anim:layer/slot/1/refresh
