# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players operation @s ml_l2rzv = @s ml_l2rzz
scoreboard players set @s ml_l2rza 0
function monolith_anim:layer/slot/2/refresh
