# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l2rza 1
scoreboard players set @s ml_l2rzt 0
scoreboard players operation @s ml_l2rzd = @s ml_lc_d
scoreboard players operation @s ml_l2rze = @s ml_le_easing
scoreboard players operation @s ml_l2rzf = @s ml_lc_f
scoreboard players operation @s ml_l2rzz = @s ml_lc_z
scoreboard players operation @s ml_l2rzv = @s ml_lc_f
execute if score @s ml_l2rzd matches 0 run function monolith_anim:layer/slot/2/rz/finish
function monolith_anim:layer/slot/2/refresh
