# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l0_path 0
scoreboard players set @s ml_l0tya 1
scoreboard players set @s ml_l0tyt 0
scoreboard players operation @s ml_l0tyd = @s ml_lc_d
scoreboard players operation @s ml_l0tye = @s ml_le_easing
scoreboard players operation @s ml_l0tyf = @s ml_lc_f
scoreboard players operation @s ml_l0tyz = @s ml_lc_z
scoreboard players operation @s ml_l0tyv = @s ml_lc_f
execute if score @s ml_l0tyd matches 0 run function monolith_anim:layer/slot/0/ty/finish
function monolith_anim:layer/slot/0/refresh
