# Generated by tools/build-transform.mjs
execute unless entity @s[type=minecraft:block_display] unless entity @s[type=minecraft:item_display] unless entity @s[type=minecraft:text_display] run return 0
execute if entity @s[tag=monolith.parent] run return 0
execute unless score #selected ml_parent_id matches 1.. run return 0
data modify storage monolith:parent_args config set value {mode:"yaw",anchor:"feet"}
$data modify storage monolith:parent_args config merge value {mode:"$(mode)",anchor:"$(anchor)"}
execute unless data storage monolith:parent_args config{mode:"position_only"} unless data storage monolith:parent_args config{mode:"yaw"} unless data storage monolith:parent_args config{mode:"full_rotation"} run return 0
execute unless data storage monolith:parent_args config{anchor:"feet"} unless data storage monolith:parent_args config{anchor:"eyes"} run return 0
scoreboard players operation @s ml_parent_ref = #selected ml_parent_id
scoreboard players set @s ml_parent_mode 0
scoreboard players set @s ml_parent_eye 0
scoreboard players set @s ml_parent_seen 0
execute if data storage monolith:parent_args config{mode:"yaw"} run scoreboard players set @s ml_parent_mode 1
execute if data storage monolith:parent_args config{mode:"full_rotation"} run scoreboard players set @s ml_parent_mode 2
execute if data storage monolith:parent_args config{anchor:"eyes"} run scoreboard players set @s ml_parent_eye 1
tag @s add monolith.child
# Persist local rotation ownership so unbind does not switch adapters mid-tween.
execute if score @s ml_r_property matches 7 run scoreboard players set @s ml_r_property 11
execute if score @s ml_r_property matches 8 run scoreboard players set @s ml_r_property 10
