# Generated by tools/build-transform.mjs
scoreboard players set @s ml_parent_seen 1
# World paths retain world position, but may still inherit parent orientation.
execute unless score @s ml_space matches 1 if score @s ml_parent_mode matches 0 run tp @s ~ ~ ~
execute unless score @s ml_space matches 1 if score @s ml_parent_mode matches 1 run tp @s ~ ~ ~ ~ 0
execute unless score @s ml_space matches 1 if score @s ml_parent_mode matches 2 run tp @s ~ ~ ~ ~ ~
execute if score @s ml_space matches 1 if score @s ml_parent_mode matches 1 positioned as @s run tp @s ~ ~ ~ ~ 0
execute if score @s ml_space matches 1 if score @s ml_parent_mode matches 2 positioned as @s run tp @s ~ ~ ~ ~ ~
