# Generated by tools/build-transform.mjs
scoreboard players set #selected ml_parent_id 0
execute if entity @s[tag=monolith_anim.node] run return 0
execute if entity @s[tag=monolith.child] run return 0
execute unless score @s ml_parent_id matches 1.. run function monolith:animation/parent/allocate
tag @s add monolith.parent
scoreboard players operation #selected ml_parent_id = @s ml_parent_id
