# Generated by tools/build-transform.mjs
# Keep the current entity and model transforms. Active tweens keep running.
tag @s remove monolith.child
scoreboard players reset @s ml_parent_ref
scoreboard players set @s ml_parent_seen 0
