# Generated by tools/build-transform.mjs
scoreboard players operation #current ml_parent_id = @s ml_parent_id
execute as @e[tag=monolith.child,scores={ml_parent_eye=0}] if score @s ml_parent_ref = #current ml_parent_id run function monolith:animation/parent/follow
execute anchored eyes positioned ^ ^ ^ as @e[tag=monolith.child,scores={ml_parent_eye=1}] if score @s ml_parent_ref = #current ml_parent_id run function monolith:animation/parent/follow
