# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l2_path 0
scoreboard players set @s ml_l2_run 0
scoreboard players set @s ml_l2txa 0
scoreboard players set @s ml_l2tya 0
scoreboard players set @s ml_l2tza 0
scoreboard players set @s ml_l2rxa 0
scoreboard players set @s ml_l2rya 0
scoreboard players set @s ml_l2rza 0
scoreboard players set @s ml_l2sxa 0
scoreboard players set @s ml_l2sya 0
scoreboard players set @s ml_l2sza 0
