# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l2_run 0
execute if score @s ml_l2_path matches 1.. run scoreboard players set @s ml_l2_run 1
execute if score @s ml_l2txa matches 1 run scoreboard players set @s ml_l2_run 1
execute if score @s ml_l2tya matches 1 run scoreboard players set @s ml_l2_run 1
execute if score @s ml_l2tza matches 1 run scoreboard players set @s ml_l2_run 1
execute if score @s ml_l2rxa matches 1 run scoreboard players set @s ml_l2_run 1
execute if score @s ml_l2rya matches 1 run scoreboard players set @s ml_l2_run 1
execute if score @s ml_l2rza matches 1 run scoreboard players set @s ml_l2_run 1
execute if score @s ml_l2sxa matches 1 run scoreboard players set @s ml_l2_run 1
execute if score @s ml_l2sya matches 1 run scoreboard players set @s ml_l2_run 1
execute if score @s ml_l2sza matches 1 run scoreboard players set @s ml_l2_run 1
