# Generated by tools/build-animation-layers.mjs
execute if score @s ml_l2_path matches 1.. run function monolith_anim:path/slot/2/tick
execute if score @s ml_l2txa matches 1 run function monolith_anim:layer/slot/2/tx/tick
execute if score @s ml_l2tya matches 1 run function monolith_anim:layer/slot/2/ty/tick
execute if score @s ml_l2tza matches 1 run function monolith_anim:layer/slot/2/tz/tick
execute if score @s ml_l2rxa matches 1 run function monolith_anim:layer/slot/2/rx/tick
execute if score @s ml_l2rya matches 1 run function monolith_anim:layer/slot/2/ry/tick
execute if score @s ml_l2rza matches 1 run function monolith_anim:layer/slot/2/rz/tick
execute if score @s ml_l2sxa matches 1 run function monolith_anim:layer/slot/2/sx/tick
execute if score @s ml_l2sya matches 1 run function monolith_anim:layer/slot/2/sy/tick
execute if score @s ml_l2sza matches 1 run function monolith_anim:layer/slot/2/sz/tick
