# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l0_path 0
scoreboard players set @s ml_l0_run 0
scoreboard players set @s ml_l0txa 0
scoreboard players set @s ml_l0tya 0
scoreboard players set @s ml_l0tza 0
scoreboard players set @s ml_l0rxa 0
scoreboard players set @s ml_l0rya 0
scoreboard players set @s ml_l0rza 0
scoreboard players set @s ml_l0sxa 0
scoreboard players set @s ml_l0sya 0
scoreboard players set @s ml_l0sza 0
