# Generated by tools/build-animation-layers.mjs
scoreboard players operation @s ml_l_tx += @s ml_l0txv
scoreboard players operation @s ml_l_ty += @s ml_l0tyv
scoreboard players operation @s ml_l_tz += @s ml_l0tzv
scoreboard players operation @s ml_l_rx += @s ml_l0rxv
scoreboard players operation @s ml_l_ry += @s ml_l0ryv
scoreboard players operation @s ml_l_rz += @s ml_l0rzv
scoreboard players operation @s ml_l_sx *= @s ml_l0sxv
scoreboard players operation @s ml_l_sx /= #unit ml_lm_k
execute if score @s ml_l_sx matches 32001.. run scoreboard players set @s ml_l_sx 32000
execute if score @s ml_l_sx matches ..-32001 run scoreboard players set @s ml_l_sx -32000
scoreboard players operation @s ml_l_sy *= @s ml_l0syv
scoreboard players operation @s ml_l_sy /= #unit ml_lm_k
execute if score @s ml_l_sy matches 32001.. run scoreboard players set @s ml_l_sy 32000
execute if score @s ml_l_sy matches ..-32001 run scoreboard players set @s ml_l_sy -32000
scoreboard players operation @s ml_l_sz *= @s ml_l0szv
scoreboard players operation @s ml_l_sz /= #unit ml_lm_k
execute if score @s ml_l_sz matches 32001.. run scoreboard players set @s ml_l_sz 32000
execute if score @s ml_l_sz matches ..-32001 run scoreboard players set @s ml_l_sz -32000
