# Generated by tools/build-animation-layers.mjs
execute if score @s ml_l0_path matches 1.. run function monolith_anim:path/slot/0/finish
execute if score @s ml_l0txa matches 1 run function monolith_anim:layer/slot/0/tx/finish
execute if score @s ml_l0tya matches 1 run function monolith_anim:layer/slot/0/ty/finish
execute if score @s ml_l0tza matches 1 run function monolith_anim:layer/slot/0/tz/finish
execute if score @s ml_l0rxa matches 1 run function monolith_anim:layer/slot/0/rx/finish
execute if score @s ml_l0rya matches 1 run function monolith_anim:layer/slot/0/ry/finish
execute if score @s ml_l0rza matches 1 run function monolith_anim:layer/slot/0/rz/finish
execute if score @s ml_l0sxa matches 1 run function monolith_anim:layer/slot/0/sx/finish
execute if score @s ml_l0sya matches 1 run function monolith_anim:layer/slot/0/sy/finish
execute if score @s ml_l0sza matches 1 run function monolith_anim:layer/slot/0/sz/finish
