# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l0_run 0
execute if score @s ml_l0_path matches 1.. run scoreboard players set @s ml_l0_run 1
execute if score @s ml_l0txa matches 1 run scoreboard players set @s ml_l0_run 1
execute if score @s ml_l0tya matches 1 run scoreboard players set @s ml_l0_run 1
execute if score @s ml_l0tza matches 1 run scoreboard players set @s ml_l0_run 1
execute if score @s ml_l0rxa matches 1 run scoreboard players set @s ml_l0_run 1
execute if score @s ml_l0rya matches 1 run scoreboard players set @s ml_l0_run 1
execute if score @s ml_l0rza matches 1 run scoreboard players set @s ml_l0_run 1
execute if score @s ml_l0sxa matches 1 run scoreboard players set @s ml_l0_run 1
execute if score @s ml_l0sya matches 1 run scoreboard players set @s ml_l0_run 1
execute if score @s ml_l0sza matches 1 run scoreboard players set @s ml_l0_run 1
