# Generated by tools/build-animation-layers.mjs
function monolith_anim:layer/slot/0/claim
execute if score @s ml_lc_prop matches 0 run function monolith_anim:layer/slot/0/tx/start
execute if score @s ml_lc_prop matches 1 run function monolith_anim:layer/slot/0/ty/start
execute if score @s ml_lc_prop matches 2 run function monolith_anim:layer/slot/0/tz/start
execute if score @s ml_lc_prop matches 3 run function monolith_anim:layer/slot/0/rx/start
execute if score @s ml_lc_prop matches 4 run function monolith_anim:layer/slot/0/ry/start
execute if score @s ml_lc_prop matches 5 run function monolith_anim:layer/slot/0/rz/start
execute if score @s ml_lc_prop matches 6 run function monolith_anim:layer/slot/0/sx/start
execute if score @s ml_lc_prop matches 7 run function monolith_anim:layer/slot/0/sy/start
execute if score @s ml_lc_prop matches 8 run function monolith_anim:layer/slot/0/sz/start
execute if score @s ml_lc_prop matches 9 run function monolith_anim:layer/slot/0/sx/start
execute if score @s ml_lc_prop matches 9 run function monolith_anim:layer/slot/0/sy/start
execute if score @s ml_lc_prop matches 9 run function monolith_anim:layer/slot/0/sz/start
