# Generated by tools/build-animation-layers.mjs
execute if score @s ml_l0_path matches 1.. run function monolith_anim:path/slot/0/tick
execute if score @s ml_l0txa matches 1 run function monolith_anim:layer/slot/0/tx/tick
execute if score @s ml_l0tya matches 1 run function monolith_anim:layer/slot/0/ty/tick
execute if score @s ml_l0tza matches 1 run function monolith_anim:layer/slot/0/tz/tick
execute if score @s ml_l0rxa matches 1 run function monolith_anim:layer/slot/0/rx/tick
execute if score @s ml_l0rya matches 1 run function monolith_anim:layer/slot/0/ry/tick
execute if score @s ml_l0rza matches 1 run function monolith_anim:layer/slot/0/rz/tick
execute if score @s ml_l0sxa matches 1 run function monolith_anim:layer/slot/0/sx/tick
execute if score @s ml_l0sya matches 1 run function monolith_anim:layer/slot/0/sy/tick
execute if score @s ml_l0sza matches 1 run function monolith_anim:layer/slot/0/sz/tick
