# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players operation @s ml_l1txv = @s ml_l1txz
scoreboard players set @s ml_l1txa 0
function monolith_anim:layer/slot/1/refresh
