# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l1_path 0
scoreboard players set @s ml_l1txa 1
scoreboard players set @s ml_l1txt 0
scoreboard players operation @s ml_l1txd = @s ml_lc_d
scoreboard players operation @s ml_l1txe = @s ml_le_easing
scoreboard players operation @s ml_l1txf = @s ml_lc_f
scoreboard players operation @s ml_l1txz = @s ml_lc_z
scoreboard players operation @s ml_l1txv = @s ml_lc_f
execute if score @s ml_l1txd matches 0 run function monolith_anim:layer/slot/1/tx/finish
function monolith_anim:layer/slot/1/refresh
