# Generated by tools/build-animation-layers.mjs
scoreboard players operation @s ml_lm_h = @s ml_lm_u
scoreboard players operation @s ml_lm_h *= @s ml_lm_u
scoreboard players operation @s ml_lm_h /= #scale ml_le_tmp0
scoreboard players operation @s ml_lm_a = @s ml_lm_u
scoreboard players operation @s ml_lm_a -= @s ml_lm_h
scoreboard players operation @s ml_lm_a *= #four ml_lm_k
scoreboard players operation @s ml_lm_h = @s ml_lm_u
scoreboard players operation @s ml_lm_u = @s ml_lm_a
scoreboard players set @s ml_lm_a 0
scoreboard players operation @s ml_lm_b = @s ml_l2_ph
function monolith_anim:math/layer_lerp
scoreboard players operation @s ml_l2tyv += @s ml_lm_v
scoreboard players operation @s ml_lm_u = @s ml_lm_h
