# Generated by tools/build-animation-layers.mjs
scoreboard players operation @s ml_lm_a = @s ml_l2_sy
scoreboard players operation @s ml_lm_b = @s ml_l2_ey
execute if score @s ml_l2_path matches 3 run scoreboard players operation @s ml_lm_b = @s ml_l2_cy
function monolith_anim:math/layer_lerp
scoreboard players operation @s ml_l2tyv = @s ml_lm_v
execute if score @s ml_l2_path matches 3 run function monolith_anim:path/slot/2/bezier_y
