# Generated by tools/build-animation-layers.mjs
scoreboard players operation @s ml_lm_a = @s ml_l2_sz
scoreboard players operation @s ml_lm_b = @s ml_l2_ez
execute if score @s ml_l2_path matches 3 run scoreboard players operation @s ml_lm_b = @s ml_l2_cz
function monolith_anim:math/layer_lerp
scoreboard players operation @s ml_l2tzv = @s ml_lm_v
execute if score @s ml_l2_path matches 3 run function monolith_anim:path/slot/2/bezier_z
