# Generated by tools/build-animation-layers.mjs
scoreboard players operation @s ml_lm_a = @s ml_l2_cz
scoreboard players operation @s ml_lm_b = @s ml_l2_ez
function monolith_anim:math/layer_lerp
scoreboard players operation @s ml_lm_a = @s ml_l2tzv
scoreboard players operation @s ml_lm_b = @s ml_lm_v
function monolith_anim:math/layer_lerp
scoreboard players operation @s ml_l2tzv = @s ml_lm_v
