# Generated by tools/build-animation-layers.mjs
function monolith_anim:path/slot/2/axis_x
function monolith_anim:path/slot/2/axis_y
function monolith_anim:path/slot/2/axis_z
execute if score @s ml_l2_path matches 2 run function monolith_anim:path/slot/2/arc
