# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players operation @s ml_l2txv = @s ml_l2_ex
scoreboard players operation @s ml_l2tyv = @s ml_l2_ey
scoreboard players operation @s ml_l2tzv = @s ml_l2_ez
scoreboard players set @s ml_l2_path 0
function monolith_anim:layer/slot/2/refresh
