# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
function monolith_anim:layer/slot/2/claim
scoreboard players set @s ml_l2txa 0
scoreboard players set @s ml_l2tya 0
scoreboard players set @s ml_l2tza 0
scoreboard players operation @s ml_l2_path = @s ml_lc_path
scoreboard players set @s ml_l2_pt 0
scoreboard players operation @s ml_l2_pd = @s ml_lc_d
scoreboard players operation @s ml_l2_pe = @s ml_le_easing
scoreboard players operation @s ml_l2_ph = @s ml_lc_h
scoreboard players operation @s ml_l2_sx = @s ml_lc_sx
scoreboard players operation @s ml_l2_ex = @s ml_lc_ex
scoreboard players operation @s ml_l2_cx = @s ml_lc_cx
scoreboard players operation @s ml_l2_sy = @s ml_lc_sy
scoreboard players operation @s ml_l2_ey = @s ml_lc_ey
scoreboard players operation @s ml_l2_cy = @s ml_lc_cy
scoreboard players operation @s ml_l2_sz = @s ml_lc_sz
scoreboard players operation @s ml_l2_ez = @s ml_lc_ez
scoreboard players operation @s ml_l2_cz = @s ml_lc_cz
scoreboard players operation @s ml_l2txv = @s ml_l2_sx
scoreboard players operation @s ml_l2tyv = @s ml_l2_sy
scoreboard players operation @s ml_l2tzv = @s ml_l2_sz
execute if score @s ml_l2_pd matches 0 run function monolith_anim:path/slot/2/finish
function monolith_anim:layer/slot/2/refresh
