# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players operation @s ml_l1rzv = @s ml_l1rzz
scoreboard players set @s ml_l1rza 0
function monolith_anim:layer/slot/1/refresh
