# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l1rza 1
scoreboard players set @s ml_l1rzt 0
scoreboard players operation @s ml_l1rzd = @s ml_lc_d
scoreboard players operation @s ml_l1rze = @s ml_le_easing
scoreboard players operation @s ml_l1rzf = @s ml_lc_f
scoreboard players operation @s ml_l1rzz = @s ml_lc_z
scoreboard players operation @s ml_l1rzv = @s ml_lc_f
execute if score @s ml_l1rzd matches 0 run function monolith_anim:layer/slot/1/rz/finish
function monolith_anim:layer/slot/1/refresh
