# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l3rya 1
scoreboard players set @s ml_l3ryt 0
scoreboard players operation @s ml_l3ryd = @s ml_lc_d
scoreboard players operation @s ml_l3rye = @s ml_le_easing
scoreboard players operation @s ml_l3ryf = @s ml_lc_f
scoreboard players operation @s ml_l3ryz = @s ml_lc_z
scoreboard players operation @s ml_l3ryv = @s ml_lc_f
execute if score @s ml_l3ryd matches 0 run function monolith_anim:layer/slot/3/ry/finish
function monolith_anim:layer/slot/3/refresh
