# Generated by tools/build-animation-debug.mjs
execute if score @s ml_seq_time matches 0 run function monolith_anim:layer/start {slot:1,property:"translation_y",from:0,to:700,duration:30,easing:"in_out_sine"}
execute if score @s ml_seq_time matches 30 run function monolith_anim:layer/start {slot:1,property:"translation_y",from:700,to:0,duration:30,easing:"in_out_sine"}
execute if score @s ml_seq_time matches 60 run function monolith_anim:layer/start {slot:1,property:"translation_y",from:0,to:700,duration:30,easing:"in_out_sine"}
execute if score @s ml_seq_time matches 90 run function monolith_anim:layer/start {slot:1,property:"translation_y",from:700,to:0,duration:30,easing:"in_out_sine"}
execute if score @s ml_seq_time matches 120 run function monolith_anim:layer/start {slot:1,property:"translation_y",from:0,to:700,duration:30,easing:"in_out_sine"}
execute if score @s ml_seq_time matches 150 run function monolith_anim:layer/start {slot:1,property:"translation_y",from:700,to:0,duration:30,easing:"in_out_sine"}
execute if score @s ml_seq_time matches 180 run function monolith_anim:layer/start {slot:1,property:"translation_y",from:0,to:700,duration:30,easing:"in_out_sine"}
execute if score @s ml_seq_time matches 210 run function monolith_anim:layer/start {slot:1,property:"translation_y",from:700,to:0,duration:30,easing:"in_out_sine"}
