# Generated by tools/build-animation-layers.mjs
scoreboard players operation @s ml_lm_a = @s ml_l3_sz
scoreboard players operation @s ml_lm_b = @s ml_l3_ez
execute if score @s ml_l3_path matches 3 run scoreboard players operation @s ml_lm_b = @s ml_l3_cz
function monolith_anim:math/layer_lerp
scoreboard players operation @s ml_l3tzv = @s ml_lm_v
execute if score @s ml_l3_path matches 3 run function monolith_anim:path/slot/3/bezier_z
