# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players operation @s ml_l3txv = @s ml_l3_ex
scoreboard players operation @s ml_l3tyv = @s ml_l3_ey
scoreboard players operation @s ml_l3tzv = @s ml_l3_ez
scoreboard players set @s ml_l3_path 0
function monolith_anim:layer/slot/3/refresh
