# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
function monolith_anim:layer/slot/3/claim
scoreboard players set @s ml_l3txa 0
scoreboard players set @s ml_l3tya 0
scoreboard players set @s ml_l3tza 0
scoreboard players operation @s ml_l3_path = @s ml_lc_path
scoreboard players set @s ml_l3_pt 0
scoreboard players operation @s ml_l3_pd = @s ml_lc_d
scoreboard players operation @s ml_l3_pe = @s ml_le_easing
scoreboard players operation @s ml_l3_ph = @s ml_lc_h
scoreboard players operation @s ml_l3_sx = @s ml_lc_sx
scoreboard players operation @s ml_l3_ex = @s ml_lc_ex
scoreboard players operation @s ml_l3_cx = @s ml_lc_cx
scoreboard players operation @s ml_l3_sy = @s ml_lc_sy
scoreboard players operation @s ml_l3_ey = @s ml_lc_ey
scoreboard players operation @s ml_l3_cy = @s ml_lc_cy
scoreboard players operation @s ml_l3_sz = @s ml_lc_sz
scoreboard players operation @s ml_l3_ez = @s ml_lc_ez
scoreboard players operation @s ml_l3_cz = @s ml_lc_cz
scoreboard players operation @s ml_l3txv = @s ml_l3_sx
scoreboard players operation @s ml_l3tyv = @s ml_l3_sy
scoreboard players operation @s ml_l3tzv = @s ml_l3_sz
execute if score @s ml_l3_pd matches 0 run function monolith_anim:path/slot/3/finish
function monolith_anim:layer/slot/3/refresh
