# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players add @s ml_l3_pt 1
execute if score @s ml_l3_pt >= @s ml_l3_pd run return run function monolith_anim:path/slot/3/finish
scoreboard players operation @s ml_le_tmp0 = @s ml_l3_pt
scoreboard players operation @s ml_le_tmp0 *= #scale ml_le_tmp0
scoreboard players operation @s ml_le_tmp0 /= @s ml_l3_pd
scoreboard players operation @s ml_le_easing = @s ml_l3_pe
function monolith_anim:easing/dispatch
scoreboard players operation @s ml_lm_u = @s ml_le_tmp1
function monolith_anim:path/slot/3/evaluate
