# Generated by tools/build-animation-layers.mjs
scoreboard players operation @s ml_lm_a = @s ml_l1_sz
scoreboard players operation @s ml_lm_b = @s ml_l1_ez
execute if score @s ml_l1_path matches 3 run scoreboard players operation @s ml_lm_b = @s ml_l1_cz
function monolith_anim:math/layer_lerp
scoreboard players operation @s ml_l1tzv = @s ml_lm_v
execute if score @s ml_l1_path matches 3 run function monolith_anim:path/slot/1/bezier_z
