# Generated by tools/build-animation-layers.mjs
scoreboard players operation @s ml_lm_a = @s ml_l1_cx
scoreboard players operation @s ml_lm_b = @s ml_l1_ex
function monolith_anim:math/layer_lerp
scoreboard players operation @s ml_lm_a = @s ml_l1txv
scoreboard players operation @s ml_lm_b = @s ml_lm_v
function monolith_anim:math/layer_lerp
scoreboard players operation @s ml_l1txv = @s ml_lm_v
