# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players operation @s ml_l1txv = @s ml_l1_ex
scoreboard players operation @s ml_l1tyv = @s ml_l1_ey
scoreboard players operation @s ml_l1tzv = @s ml_l1_ez
scoreboard players set @s ml_l1_path 0
function monolith_anim:layer/slot/1/refresh
