# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
function monolith_anim:layer/slot/1/claim
scoreboard players set @s ml_l1txa 0
scoreboard players set @s ml_l1tya 0
scoreboard players set @s ml_l1tza 0
scoreboard players operation @s ml_l1_path = @s ml_lc_path
scoreboard players set @s ml_l1_pt 0
scoreboard players operation @s ml_l1_pd = @s ml_lc_d
scoreboard players operation @s ml_l1_pe = @s ml_le_easing
scoreboard players operation @s ml_l1_ph = @s ml_lc_h
scoreboard players operation @s ml_l1_sx = @s ml_lc_sx
scoreboard players operation @s ml_l1_ex = @s ml_lc_ex
scoreboard players operation @s ml_l1_cx = @s ml_lc_cx
scoreboard players operation @s ml_l1_sy = @s ml_lc_sy
scoreboard players operation @s ml_l1_ey = @s ml_lc_ey
scoreboard players operation @s ml_l1_cy = @s ml_lc_cy
scoreboard players operation @s ml_l1_sz = @s ml_lc_sz
scoreboard players operation @s ml_l1_ez = @s ml_lc_ez
scoreboard players operation @s ml_l1_cz = @s ml_lc_cz
scoreboard players operation @s ml_l1txv = @s ml_l1_sx
scoreboard players operation @s ml_l1tyv = @s ml_l1_sy
scoreboard players operation @s ml_l1tzv = @s ml_l1_sz
execute if score @s ml_l1_pd matches 0 run function monolith_anim:path/slot/1/finish
function monolith_anim:layer/slot/1/refresh
