# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players operation @s ml_l2ryv = @s ml_l2ryz
scoreboard players set @s ml_l2rya 0
function monolith_anim:layer/slot/2/refresh
