# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l2rya 1
scoreboard players set @s ml_l2ryt 0
scoreboard players operation @s ml_l2ryd = @s ml_lc_d
scoreboard players operation @s ml_l2rye = @s ml_le_easing
scoreboard players operation @s ml_l2ryf = @s ml_lc_f
scoreboard players operation @s ml_l2ryz = @s ml_lc_z
scoreboard players operation @s ml_l2ryv = @s ml_lc_f
execute if score @s ml_l2ryd matches 0 run function monolith_anim:layer/slot/2/ry/finish
function monolith_anim:layer/slot/2/refresh
