# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players add @s ml_l2ryt 1
execute if score @s ml_l2ryt >= @s ml_l2ryd run return run function monolith_anim:layer/slot/2/ry/finish
scoreboard players operation @s ml_le_tmp0 = @s ml_l2ryt
scoreboard players operation @s ml_le_tmp0 *= #scale ml_le_tmp0
scoreboard players operation @s ml_le_tmp0 /= @s ml_l2ryd
scoreboard players operation @s ml_le_easing = @s ml_l2rye
function monolith_anim:easing/dispatch
scoreboard players operation @s ml_lm_u = @s ml_le_tmp1
scoreboard players operation @s ml_lm_a = @s ml_l2ryf
scoreboard players operation @s ml_lm_b = @s ml_l2ryz
function monolith_anim:math/layer_lerp
scoreboard players operation @s ml_l2ryv = @s ml_lm_v
