# Generated by tools/build-animation-debug.mjs
execute if score @s ml_seq_time matches 0 run function monolith_anim:layer/start {slot:0,property:"scale_xyz",from:300,to:1000,duration:40,easing:"out_back"}
execute if score @s ml_seq_time matches 0 run function monolith_anim:layer/start {slot:0,property:"rotation_z",from:-45000,to:0,duration:40,easing:"out_quart"}
execute if score @s ml_seq_time matches 0 run particle minecraft:happy_villager ~ ~1 ~ 0.4 0.4 0.4 0 12 force
