# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l3_path 0
scoreboard players set @s ml_l3_run 0
scoreboard players set @s ml_l3txa 0
scoreboard players set @s ml_l3tya 0
scoreboard players set @s ml_l3tza 0
scoreboard players set @s ml_l3rxa 0
scoreboard players set @s ml_l3rya 0
scoreboard players set @s ml_l3rza 0
scoreboard players set @s ml_l3sxa 0
scoreboard players set @s ml_l3sya 0
scoreboard players set @s ml_l3sza 0
