# Generated by tools/build-animation-layers.mjs
execute if score @s ml_l3_path matches 1.. run function monolith_anim:path/slot/3/finish
execute if score @s ml_l3txa matches 1 run function monolith_anim:layer/slot/3/tx/finish
execute if score @s ml_l3tya matches 1 run function monolith_anim:layer/slot/3/ty/finish
execute if score @s ml_l3tza matches 1 run function monolith_anim:layer/slot/3/tz/finish
execute if score @s ml_l3rxa matches 1 run function monolith_anim:layer/slot/3/rx/finish
execute if score @s ml_l3rya matches 1 run function monolith_anim:layer/slot/3/ry/finish
execute if score @s ml_l3rza matches 1 run function monolith_anim:layer/slot/3/rz/finish
execute if score @s ml_l3sxa matches 1 run function monolith_anim:layer/slot/3/sx/finish
execute if score @s ml_l3sya matches 1 run function monolith_anim:layer/slot/3/sy/finish
execute if score @s ml_l3sza matches 1 run function monolith_anim:layer/slot/3/sz/finish
