# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l3_run 0
execute if score @s ml_l3_path matches 1.. run scoreboard players set @s ml_l3_run 1
execute if score @s ml_l3txa matches 1 run scoreboard players set @s ml_l3_run 1
execute if score @s ml_l3tya matches 1 run scoreboard players set @s ml_l3_run 1
execute if score @s ml_l3tza matches 1 run scoreboard players set @s ml_l3_run 1
execute if score @s ml_l3rxa matches 1 run scoreboard players set @s ml_l3_run 1
execute if score @s ml_l3rya matches 1 run scoreboard players set @s ml_l3_run 1
execute if score @s ml_l3rza matches 1 run scoreboard players set @s ml_l3_run 1
execute if score @s ml_l3sxa matches 1 run scoreboard players set @s ml_l3_run 1
execute if score @s ml_l3sya matches 1 run scoreboard players set @s ml_l3_run 1
execute if score @s ml_l3sza matches 1 run scoreboard players set @s ml_l3_run 1
