# Generated by tools/build-animation-layers.mjs
function monolith_anim:layer/slot/3/claim
execute if score @s ml_lc_prop matches 0 run function monolith_anim:layer/slot/3/tx/start
execute if score @s ml_lc_prop matches 1 run function monolith_anim:layer/slot/3/ty/start
execute if score @s ml_lc_prop matches 2 run function monolith_anim:layer/slot/3/tz/start
execute if score @s ml_lc_prop matches 3 run function monolith_anim:layer/slot/3/rx/start
execute if score @s ml_lc_prop matches 4 run function monolith_anim:layer/slot/3/ry/start
execute if score @s ml_lc_prop matches 5 run function monolith_anim:layer/slot/3/rz/start
execute if score @s ml_lc_prop matches 6 run function monolith_anim:layer/slot/3/sx/start
execute if score @s ml_lc_prop matches 7 run function monolith_anim:layer/slot/3/sy/start
execute if score @s ml_lc_prop matches 8 run function monolith_anim:layer/slot/3/sz/start
execute if score @s ml_lc_prop matches 9 run function monolith_anim:layer/slot/3/sx/start
execute if score @s ml_lc_prop matches 9 run function monolith_anim:layer/slot/3/sy/start
execute if score @s ml_lc_prop matches 9 run function monolith_anim:layer/slot/3/sz/start
