# Generated by tools/build-animation-layers.mjs
execute if score @s ml_l3_path matches 1.. run function monolith_anim:path/slot/3/tick
execute if score @s ml_l3txa matches 1 run function monolith_anim:layer/slot/3/tx/tick
execute if score @s ml_l3tya matches 1 run function monolith_anim:layer/slot/3/ty/tick
execute if score @s ml_l3tza matches 1 run function monolith_anim:layer/slot/3/tz/tick
execute if score @s ml_l3rxa matches 1 run function monolith_anim:layer/slot/3/rx/tick
execute if score @s ml_l3rya matches 1 run function monolith_anim:layer/slot/3/ry/tick
execute if score @s ml_l3rza matches 1 run function monolith_anim:layer/slot/3/rz/tick
execute if score @s ml_l3sxa matches 1 run function monolith_anim:layer/slot/3/sx/tick
execute if score @s ml_l3sya matches 1 run function monolith_anim:layer/slot/3/sy/tick
execute if score @s ml_l3sza matches 1 run function monolith_anim:layer/slot/3/sz/tick
