# Generated by tools/build-animation-layers.mjs
scoreboard players operation @s ml_le_tmp1 = @s ml_le_lut_a
scoreboard players operation @s ml_le_tmp1 -= @s ml_le_lut_b
scoreboard players operation @s ml_le_tmp1 *= @s ml_le_lut_r
scoreboard players operation @s ml_le_tmp1 /= #lut_step ml_le_tmp0
scoreboard players operation @s ml_le_tmp1 += @s ml_le_lut_b
