# Generated by tools/build-animation-layers.mjs
scoreboard players operation @s ml_le_lut_i = @s ml_le_tmp0
scoreboard players operation @s ml_le_lut_i /= #lut_step ml_le_tmp0
scoreboard players operation @s ml_le_lut_r = @s ml_le_tmp0
scoreboard players operation @s ml_le_lut_r %= #lut_step ml_le_tmp0
