# Generated by tools/build-animation-debug.mjs
# --- 0t : Curve away from the original anchor ---
execute if score @s ml_seq_time matches 0 run function monolith_anim:path/bezier {slot:0,sx:0,sy:0,sz:0,cx:3000,cy:2000,cz:0,ex:4000,ey:0,ez:2000,duration:120,easing:"in_out_sine"}
# --- 120t : Return ---
execute if score @s ml_seq_time matches 120 run function monolith_anim:path/arc {slot:0,sx:4000,sy:0,sz:2000,ex:0,ey:0,ez:0,height:1500,duration:120,easing:"in_out_sine"}
