# Generated by tools/build-transform.mjs
scoreboard players operation @s ml_path_w = @s ml_path_b
scoreboard players operation @s ml_path_w -= @s ml_path_a
scoreboard players operation @s ml_path_v = @s ml_path_w
scoreboard players operation @s ml_path_v /= #scale ml_a_tmp0
scoreboard players operation @s ml_path_v *= @s ml_path_u
scoreboard players operation @s ml_path_w %= #scale ml_a_tmp0
scoreboard players operation @s ml_path_w *= @s ml_path_u
scoreboard players operation @s ml_path_w /= #scale ml_a_tmp0
scoreboard players operation @s ml_path_v += @s ml_path_w
scoreboard players operation @s ml_path_v += @s ml_path_a
