# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players operation @s ml_l3rxv = @s ml_l3rxz
scoreboard players set @s ml_l3rxa 0
function monolith_anim:layer/slot/3/refresh
