# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l3rxa 1
scoreboard players set @s ml_l3rxt 0
scoreboard players operation @s ml_l3rxd = @s ml_lc_d
scoreboard players operation @s ml_l3rxe = @s ml_le_easing
scoreboard players operation @s ml_l3rxf = @s ml_lc_f
scoreboard players operation @s ml_l3rxz = @s ml_lc_z
scoreboard players operation @s ml_l3rxv = @s ml_lc_f
execute if score @s ml_l3rxd matches 0 run function monolith_anim:layer/slot/3/rx/finish
function monolith_anim:layer/slot/3/refresh
