# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players add @s ml_l3rxt 1
execute if score @s ml_l3rxt >= @s ml_l3rxd run return run function monolith_anim:layer/slot/3/rx/finish
scoreboard players operation @s ml_le_tmp0 = @s ml_l3rxt
scoreboard players operation @s ml_le_tmp0 *= #scale ml_le_tmp0
scoreboard players operation @s ml_le_tmp0 /= @s ml_l3rxd
scoreboard players operation @s ml_le_easing = @s ml_l3rxe
function monolith_anim:easing/dispatch
scoreboard players operation @s ml_lm_u = @s ml_le_tmp1
scoreboard players operation @s ml_lm_a = @s ml_l3rxf
scoreboard players operation @s ml_lm_b = @s ml_l3rxz
function monolith_anim:math/layer_lerp
scoreboard players operation @s ml_l3rxv = @s ml_lm_v
