# Generated by tools/build-animation-nodes.mjs
# Extrinsic X then Y then Z: q = qZ * qY * qX. Positive angles are right handed.
scoreboard players operation @s ml_n_angle = @s ml_n_ex
function monolith_anim:node/math/sincos
scoreboard players operation @s ml_n_sinx = @s ml_n_s0
scoreboard players operation @s ml_n_cosx = @s ml_n_c0
scoreboard players operation @s ml_n_angle = @s ml_n_ey
function monolith_anim:node/math/sincos
scoreboard players operation @s ml_n_siny = @s ml_n_s0
scoreboard players operation @s ml_n_cosy = @s ml_n_c0
scoreboard players operation @s ml_n_angle = @s ml_n_ez
function monolith_anim:node/math/sincos
scoreboard players operation @s ml_n_sinz = @s ml_n_s0
scoreboard players operation @s ml_n_cosz = @s ml_n_c0
scoreboard players set @s ml_n_ax 0
scoreboard players operation @s ml_n_ay = @s ml_n_siny
scoreboard players set @s ml_n_az 0
scoreboard players operation @s ml_n_aw = @s ml_n_cosy
scoreboard players operation @s ml_n_bx = @s ml_n_sinx
scoreboard players set @s ml_n_by 0
scoreboard players set @s ml_n_bz 0
scoreboard players operation @s ml_n_bw = @s ml_n_cosx
function monolith_anim:node/math/multiply
scoreboard players operation @s ml_n_bx = @s ml_n_qx
scoreboard players operation @s ml_n_by = @s ml_n_qy
scoreboard players operation @s ml_n_bz = @s ml_n_qz
scoreboard players operation @s ml_n_bw = @s ml_n_qw
scoreboard players set @s ml_n_ax 0
scoreboard players set @s ml_n_ay 0
scoreboard players operation @s ml_n_az = @s ml_n_sinz
scoreboard players operation @s ml_n_aw = @s ml_n_cosz
function monolith_anim:node/math/multiply
function monolith_anim:node/math/normalize
