# Generated by tools/build-animation-nodes.mjs
scoreboard players set @s ml_n_qx 0
scoreboard players operation @s ml_n_tmp = @s ml_n_aw
scoreboard players operation @s ml_n_tmp *= @s ml_n_bx
scoreboard players operation @s ml_n_qx += @s ml_n_tmp
scoreboard players operation @s ml_n_tmp = @s ml_n_ax
scoreboard players operation @s ml_n_tmp *= @s ml_n_bw
scoreboard players operation @s ml_n_qx += @s ml_n_tmp
scoreboard players operation @s ml_n_tmp = @s ml_n_ay
scoreboard players operation @s ml_n_tmp *= @s ml_n_bz
scoreboard players operation @s ml_n_qx += @s ml_n_tmp
scoreboard players operation @s ml_n_tmp = @s ml_n_az
scoreboard players operation @s ml_n_tmp *= @s ml_n_by
scoreboard players operation @s ml_n_qx -= @s ml_n_tmp
scoreboard players operation @s ml_n_qx /= #unit ml_n_math
scoreboard players set @s ml_n_qy 0
scoreboard players operation @s ml_n_tmp = @s ml_n_aw
scoreboard players operation @s ml_n_tmp *= @s ml_n_by
scoreboard players operation @s ml_n_qy += @s ml_n_tmp
scoreboard players operation @s ml_n_tmp = @s ml_n_ax
scoreboard players operation @s ml_n_tmp *= @s ml_n_bz
scoreboard players operation @s ml_n_qy -= @s ml_n_tmp
scoreboard players operation @s ml_n_tmp = @s ml_n_ay
scoreboard players operation @s ml_n_tmp *= @s ml_n_bw
scoreboard players operation @s ml_n_qy += @s ml_n_tmp
scoreboard players operation @s ml_n_tmp = @s ml_n_az
scoreboard players operation @s ml_n_tmp *= @s ml_n_bx
scoreboard players operation @s ml_n_qy += @s ml_n_tmp
scoreboard players operation @s ml_n_qy /= #unit ml_n_math
scoreboard players set @s ml_n_qz 0
scoreboard players operation @s ml_n_tmp = @s ml_n_aw
scoreboard players operation @s ml_n_tmp *= @s ml_n_bz
scoreboard players operation @s ml_n_qz += @s ml_n_tmp
scoreboard players operation @s ml_n_tmp = @s ml_n_ax
scoreboard players operation @s ml_n_tmp *= @s ml_n_by
scoreboard players operation @s ml_n_qz += @s ml_n_tmp
scoreboard players operation @s ml_n_tmp = @s ml_n_ay
scoreboard players operation @s ml_n_tmp *= @s ml_n_bx
scoreboard players operation @s ml_n_qz -= @s ml_n_tmp
scoreboard players operation @s ml_n_tmp = @s ml_n_az
scoreboard players operation @s ml_n_tmp *= @s ml_n_bw
scoreboard players operation @s ml_n_qz += @s ml_n_tmp
scoreboard players operation @s ml_n_qz /= #unit ml_n_math
scoreboard players set @s ml_n_qw 0
scoreboard players operation @s ml_n_tmp = @s ml_n_aw
scoreboard players operation @s ml_n_tmp *= @s ml_n_bw
scoreboard players operation @s ml_n_qw += @s ml_n_tmp
scoreboard players operation @s ml_n_tmp = @s ml_n_ax
scoreboard players operation @s ml_n_tmp *= @s ml_n_bx
scoreboard players operation @s ml_n_qw -= @s ml_n_tmp
scoreboard players operation @s ml_n_tmp = @s ml_n_ay
scoreboard players operation @s ml_n_tmp *= @s ml_n_by
scoreboard players operation @s ml_n_qw -= @s ml_n_tmp
scoreboard players operation @s ml_n_tmp = @s ml_n_az
scoreboard players operation @s ml_n_tmp *= @s ml_n_bz
scoreboard players operation @s ml_n_qw -= @s ml_n_tmp
scoreboard players operation @s ml_n_qw /= #unit ml_n_math
