# Generated by tools/build-animation-nodes.mjs
scoreboard players set @s ml_n_norm 0
scoreboard players operation @s ml_n_tmp = @s ml_n_qx
scoreboard players operation @s ml_n_tmp *= @s ml_n_qx
scoreboard players operation @s ml_n_norm += @s ml_n_tmp
scoreboard players operation @s ml_n_tmp = @s ml_n_qy
scoreboard players operation @s ml_n_tmp *= @s ml_n_qy
scoreboard players operation @s ml_n_norm += @s ml_n_tmp
scoreboard players operation @s ml_n_tmp = @s ml_n_qz
scoreboard players operation @s ml_n_tmp *= @s ml_n_qz
scoreboard players operation @s ml_n_norm += @s ml_n_tmp
scoreboard players operation @s ml_n_tmp = @s ml_n_qw
scoreboard players operation @s ml_n_tmp *= @s ml_n_qw
scoreboard players operation @s ml_n_norm += @s ml_n_tmp
scoreboard players operation @s ml_n_norm /= #unit ml_n_math
scoreboard players set @s ml_n_factor 30000
scoreboard players operation @s ml_n_factor -= @s ml_n_norm
scoreboard players operation @s ml_n_factor /= #two ml_n_math
scoreboard players operation @s ml_n_qx *= @s ml_n_factor
scoreboard players operation @s ml_n_qx /= #unit ml_n_math
scoreboard players operation @s ml_n_qy *= @s ml_n_factor
scoreboard players operation @s ml_n_qy /= #unit ml_n_math
scoreboard players operation @s ml_n_qz *= @s ml_n_factor
scoreboard players operation @s ml_n_qz /= #unit ml_n_math
scoreboard players operation @s ml_n_qw *= @s ml_n_factor
scoreboard players operation @s ml_n_qw /= #unit ml_n_math
