# Generated by tools/build-animation-nodes.mjs
$execute store result score @s ml_n_s0 run data get storage monolith_anim:node_lut values[$(i)].s 1
$execute store result score @s ml_n_s1 run data get storage monolith_anim:node_lut values[$(j)].s 1
$execute store result score @s ml_n_c0 run data get storage monolith_anim:node_lut values[$(i)].c 1
$execute store result score @s ml_n_c1 run data get storage monolith_anim:node_lut values[$(j)].c 1
