# Generated by tools/build-animation-nodes.mjs
scoreboard players operation @s ml_n_i = @s ml_n_angle
scoreboard players operation @s ml_n_i %= #turn ml_n_math
scoreboard players operation @s ml_n_rem = @s ml_n_i
scoreboard players operation @s ml_n_rem %= #degree ml_n_math
scoreboard players operation @s ml_n_i /= #degree ml_n_math
scoreboard players operation @s ml_n_j = @s ml_n_i
scoreboard players add @s ml_n_j 1
execute store result storage monolith_anim:node_math i int 1 run scoreboard players get @s ml_n_i
execute store result storage monolith_anim:node_math j int 1 run scoreboard players get @s ml_n_j
function monolith_anim:node/math/read with storage monolith_anim:node_math
scoreboard players operation @s ml_n_s1 -= @s ml_n_s0
scoreboard players operation @s ml_n_s1 *= @s ml_n_rem
scoreboard players operation @s ml_n_s1 /= #degree ml_n_math
scoreboard players operation @s ml_n_s0 += @s ml_n_s1
scoreboard players operation @s ml_n_c1 -= @s ml_n_c0
scoreboard players operation @s ml_n_c1 *= @s ml_n_rem
scoreboard players operation @s ml_n_c1 /= #degree ml_n_math
scoreboard players operation @s ml_n_c0 += @s ml_n_c1
