# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l2sya 1
scoreboard players set @s ml_l2syt 0
scoreboard players operation @s ml_l2syd = @s ml_lc_d
scoreboard players operation @s ml_l2sye = @s ml_le_easing
scoreboard players operation @s ml_l2syf = @s ml_lc_f
scoreboard players operation @s ml_l2syz = @s ml_lc_z
scoreboard players operation @s ml_l2syv = @s ml_lc_f
execute if score @s ml_l2syd matches 0 run function monolith_anim:layer/slot/2/sy/finish
function monolith_anim:layer/slot/2/refresh
