# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l1_path 0
scoreboard players set @s ml_l1_run 0
scoreboard players set @s ml_l1txa 0
scoreboard players set @s ml_l1tya 0
scoreboard players set @s ml_l1tza 0
scoreboard players set @s ml_l1rxa 0
scoreboard players set @s ml_l1rya 0
scoreboard players set @s ml_l1rza 0
scoreboard players set @s ml_l1sxa 0
scoreboard players set @s ml_l1sya 0
scoreboard players set @s ml_l1sza 0
