# Generated by tools/build-animation-layers.mjs
execute if score @s ml_l1_path matches 1.. run function monolith_anim:path/slot/1/finish
execute if score @s ml_l1txa matches 1 run function monolith_anim:layer/slot/1/tx/finish
execute if score @s ml_l1tya matches 1 run function monolith_anim:layer/slot/1/ty/finish
execute if score @s ml_l1tza matches 1 run function monolith_anim:layer/slot/1/tz/finish
execute if score @s ml_l1rxa matches 1 run function monolith_anim:layer/slot/1/rx/finish
execute if score @s ml_l1rya matches 1 run function monolith_anim:layer/slot/1/ry/finish
execute if score @s ml_l1rza matches 1 run function monolith_anim:layer/slot/1/rz/finish
execute if score @s ml_l1sxa matches 1 run function monolith_anim:layer/slot/1/sx/finish
execute if score @s ml_l1sya matches 1 run function monolith_anim:layer/slot/1/sy/finish
execute if score @s ml_l1sza matches 1 run function monolith_anim:layer/slot/1/sz/finish
