# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l1_run 0
execute if score @s ml_l1_path matches 1.. run scoreboard players set @s ml_l1_run 1
execute if score @s ml_l1txa matches 1 run scoreboard players set @s ml_l1_run 1
execute if score @s ml_l1tya matches 1 run scoreboard players set @s ml_l1_run 1
execute if score @s ml_l1tza matches 1 run scoreboard players set @s ml_l1_run 1
execute if score @s ml_l1rxa matches 1 run scoreboard players set @s ml_l1_run 1
execute if score @s ml_l1rya matches 1 run scoreboard players set @s ml_l1_run 1
execute if score @s ml_l1rza matches 1 run scoreboard players set @s ml_l1_run 1
execute if score @s ml_l1sxa matches 1 run scoreboard players set @s ml_l1_run 1
execute if score @s ml_l1sya matches 1 run scoreboard players set @s ml_l1_run 1
execute if score @s ml_l1sza matches 1 run scoreboard players set @s ml_l1_run 1
