# Generated by tools/build-animation-layers.mjs
execute if score @s ml_l1_path matches 1.. run function monolith_anim:path/slot/1/tick
execute if score @s ml_l1txa matches 1 run function monolith_anim:layer/slot/1/tx/tick
execute if score @s ml_l1tya matches 1 run function monolith_anim:layer/slot/1/ty/tick
execute if score @s ml_l1tza matches 1 run function monolith_anim:layer/slot/1/tz/tick
execute if score @s ml_l1rxa matches 1 run function monolith_anim:layer/slot/1/rx/tick
execute if score @s ml_l1rya matches 1 run function monolith_anim:layer/slot/1/ry/tick
execute if score @s ml_l1rza matches 1 run function monolith_anim:layer/slot/1/rz/tick
execute if score @s ml_l1sxa matches 1 run function monolith_anim:layer/slot/1/sx/tick
execute if score @s ml_l1sya matches 1 run function monolith_anim:layer/slot/1/sy/tick
execute if score @s ml_l1sza matches 1 run function monolith_anim:layer/slot/1/sz/tick
