# Generated by tools/build-animation-layers.mjs
scoreboard players operation @s ml_lm_a = @s ml_l0_cy
scoreboard players operation @s ml_lm_b = @s ml_l0_ey
function monolith_anim:math/layer_lerp
scoreboard players operation @s ml_lm_a = @s ml_l0tyv
scoreboard players operation @s ml_lm_b = @s ml_lm_v
function monolith_anim:math/layer_lerp
scoreboard players operation @s ml_l0tyv = @s ml_lm_v
