# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players operation @s ml_l0txv = @s ml_l0_ex
scoreboard players operation @s ml_l0tyv = @s ml_l0_ey
scoreboard players operation @s ml_l0tzv = @s ml_l0_ez
scoreboard players set @s ml_l0_path 0
function monolith_anim:layer/slot/0/refresh
