# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
function monolith_anim:layer/slot/0/claim
scoreboard players set @s ml_l0txa 0
scoreboard players set @s ml_l0tya 0
scoreboard players set @s ml_l0tza 0
scoreboard players operation @s ml_l0_path = @s ml_lc_path
scoreboard players set @s ml_l0_pt 0
scoreboard players operation @s ml_l0_pd = @s ml_lc_d
scoreboard players operation @s ml_l0_pe = @s ml_le_easing
scoreboard players operation @s ml_l0_ph = @s ml_lc_h
scoreboard players operation @s ml_l0_sx = @s ml_lc_sx
scoreboard players operation @s ml_l0_ex = @s ml_lc_ex
scoreboard players operation @s ml_l0_cx = @s ml_lc_cx
scoreboard players operation @s ml_l0_sy = @s ml_lc_sy
scoreboard players operation @s ml_l0_ey = @s ml_lc_ey
scoreboard players operation @s ml_l0_cy = @s ml_lc_cy
scoreboard players operation @s ml_l0_sz = @s ml_lc_sz
scoreboard players operation @s ml_l0_ez = @s ml_lc_ez
scoreboard players operation @s ml_l0_cz = @s ml_lc_cz
scoreboard players operation @s ml_l0txv = @s ml_l0_sx
scoreboard players operation @s ml_l0tyv = @s ml_l0_sy
scoreboard players operation @s ml_l0tzv = @s ml_l0_sz
execute if score @s ml_l0_pd matches 0 run function monolith_anim:path/slot/0/finish
function monolith_anim:layer/slot/0/refresh
