# Generated by tools/build-animation-layers.mjs
function monolith_anim:layer/init
scoreboard players set @s ml_l_ok 0
scoreboard players set @s ml_l_slot -1
execute if score @s ml_l0_used matches 0 run return run function monolith_anim:layer/slot/0/claim
execute if score @s ml_l1_used matches 0 run return run function monolith_anim:layer/slot/1/claim
execute if score @s ml_l2_used matches 0 run return run function monolith_anim:layer/slot/2/claim
execute if score @s ml_l3_used matches 0 run return run function monolith_anim:layer/slot/3/claim
return 0
