# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_ok 0
$scoreboard players set @s ml_l_slot $(slot)
execute unless score @s ml_l_slot matches 0..3 run return 0
function monolith_anim:layer/init
execute if score @s ml_l_slot matches 0 run function monolith_anim:layer/slot/0/clear
execute if score @s ml_l_slot matches 1 run function monolith_anim:layer/slot/1/clear
execute if score @s ml_l_slot matches 2 run function monolith_anim:layer/slot/2/clear
execute if score @s ml_l_slot matches 3 run function monolith_anim:layer/slot/3/clear
function monolith_anim:layer/compose
scoreboard players set @s ml_l_ok 1
return 1
