# Generated by tools/build-animation-layers.mjs
execute if score @s ml_l_dirty matches 0 run return 1
scoreboard players set @s ml_l_dirty 0
scoreboard players set @s ml_l_tx 0
scoreboard players set @s ml_l_ty 0
scoreboard players set @s ml_l_tz 0
scoreboard players set @s ml_l_rx 0
scoreboard players set @s ml_l_ry 0
scoreboard players set @s ml_l_rz 0
scoreboard players set @s ml_l_sx 1000
scoreboard players set @s ml_l_sy 1000
scoreboard players set @s ml_l_sz 1000
execute if score @s ml_l0_used matches 1 run function monolith_anim:layer/slot/0/compose
execute if score @s ml_l1_used matches 1 run function monolith_anim:layer/slot/1/compose
execute if score @s ml_l2_used matches 1 run function monolith_anim:layer/slot/2/compose
execute if score @s ml_l3_used matches 1 run function monolith_anim:layer/slot/3/compose
