# Generated by tools/build-animation-layers.mjs
execute if entity @s[tag=monolith_anim.layers] run return 1
function monolith_anim:layer/slot/0/clear
function monolith_anim:layer/slot/1/clear
function monolith_anim:layer/slot/2/clear
function monolith_anim:layer/slot/3/clear
tag @s add monolith_anim.layers
function monolith_anim:layer/compose
