# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_ok 0
scoreboard players set @s ml_lc_prop -1
scoreboard players set @s ml_le_easing -1
$function monolith_anim:layer/property/$(property)
$function monolith_anim:easing/resolve/$(easing)
execute unless score @s ml_lc_prop matches 0..9 run return 0
execute unless score @s ml_le_easing matches 0..30 run return 0
$scoreboard players set @s ml_lc_f $(from)
$scoreboard players set @s ml_lc_z $(to)
$scoreboard players set @s ml_lc_d $(duration)
execute unless score @s ml_lc_d matches 0..200000 run return 0
execute if score @s ml_lc_prop matches 0..2 unless score @s ml_lc_f matches -1000000..1000000 run return 0
execute if score @s ml_lc_prop matches 3..5 unless score @s ml_lc_f matches -3600000..3600000 run return 0
execute if score @s ml_lc_prop matches 6..9 unless score @s ml_lc_f matches -8000..8000 run return 0
execute if score @s ml_lc_prop matches 0..2 unless score @s ml_lc_z matches -1000000..1000000 run return 0
execute if score @s ml_lc_prop matches 3..5 unless score @s ml_lc_z matches -3600000..3600000 run return 0
execute if score @s ml_lc_prop matches 6..9 unless score @s ml_lc_z matches -8000..8000 run return 0
function monolith_anim:layer/allocate
execute unless score @s ml_l_slot matches 0..3 run return 0
execute if score @s ml_l_slot matches 0 run function monolith_anim:layer/slot/0/start
execute if score @s ml_l_slot matches 1 run function monolith_anim:layer/slot/1/start
execute if score @s ml_l_slot matches 2 run function monolith_anim:layer/slot/2/start
execute if score @s ml_l_slot matches 3 run function monolith_anim:layer/slot/3/start
function monolith_anim:layer/compose
return 1
