# Generated by tools/build-animation-layers.mjs
execute if score @s ml_l0_run matches 1 unless score @s ml_l0_pause matches 1 run function monolith_anim:layer/slot/0/tick
execute if score @s ml_l1_run matches 1 unless score @s ml_l1_pause matches 1 run function monolith_anim:layer/slot/1/tick
execute if score @s ml_l2_run matches 1 unless score @s ml_l2_pause matches 1 run function monolith_anim:layer/slot/2/tick
execute if score @s ml_l3_run matches 1 unless score @s ml_l3_pause matches 1 run function monolith_anim:layer/slot/3/tick
function monolith_anim:layer/compose
