# Generated by tools/build-animation-debug.mjs
# --- 0t : Wait for entrance; the sequencer resumes at time 1 exactly once. ---
execute if score @s ml_seq_time matches 0 run function monolith_anim:sequence/child {id:"monolith:demo/entrance",mode:"wait"}
# --- 1t : Two independent children on separate layers. ---
execute if score @s ml_seq_time matches 1 run function monolith_anim:sequence/child {id:"monolith:demo/part",mode:"parallel"}
execute if score @s ml_seq_time matches 1 run function monolith_anim:sequence/child {id:"monolith:demo/bob",mode:"parallel"}
