# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players operation @s ml_l2txv = @s ml_l2txz
scoreboard players set @s ml_l2txa 0
function monolith_anim:layer/slot/2/refresh
