# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l2_path 0
scoreboard players set @s ml_l2txa 1
scoreboard players set @s ml_l2txt 0
scoreboard players operation @s ml_l2txd = @s ml_lc_d
scoreboard players operation @s ml_l2txe = @s ml_le_easing
scoreboard players operation @s ml_l2txf = @s ml_lc_f
scoreboard players operation @s ml_l2txz = @s ml_lc_z
scoreboard players operation @s ml_l2txv = @s ml_lc_f
execute if score @s ml_l2txd matches 0 run function monolith_anim:layer/slot/2/tx/finish
function monolith_anim:layer/slot/2/refresh
