# Generated by tools/build-animation-debug.mjs
function monolith:animation/demo/reset
function monolith:animation/demo/definitions
execute positioned ^ ^ ^5 summon minecraft:block_display run function monolith:animation/demo/create_master
