# Generated by tools/build-animation-debug.mjs
function monolith_anim:parent/select
execute summon minecraft:block_display run function monolith:animation/demo/create_part {x:-2200,block:"minecraft:amethyst_block"}
execute summon minecraft:block_display run function monolith:animation/demo/create_part {x:2200,block:"minecraft:gold_block"}
