# Generated by tools/build-animation-debug.mjs
tag @s add monolith.anim_demo
tag @s add monolith.anim_demo.part
$data merge entity @s {block_state:{Name:"$(block)"},transformation:{translation:[0f,0f,0f],scale:[1f,1f,1f],left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f]}}
function monolith_anim:node/init
$function monolith_anim:node/base {tx:$(x),ty:0,tz:0,rx:0,ry:0,rz:0,sx:600,sy:600,sz:600}
function monolith_anim:parent/bind {mode:"full_rotation",anchor:"feet"}
function monolith_anim:sequence/start {id:"monolith:demo/part"}
function monolith_anim:sequence/start {id:"monolith:demo/bob"}
