# Generated by tools/build-animation-debug.mjs
tag @s add monolith.anim_demo
tag @s add monolith.anim_demo.root
function monolith_anim:node/init
function monolith_anim:node/base {tx:0,ty:0,tz:0,rx:0,ry:0,rz:0,sx:1000,sy:1000,sz:1000}
function monolith_anim:sequence/start {id:"monolith:demo/root"}
