# Generated by tools/build-animation-debug.mjs
function monolith_anim:parent/select
execute summon minecraft:marker run function monolith:animation/demo/create_orbit
execute as @e[type=minecraft:marker,tag=monolith.anim_demo.orbit,limit=1] at @s run function monolith:animation/demo/create_parts
