# Generated by tools/build-animation-debug.mjs
function monolith_anim:sequence/define {id:"monolith:demo/root",definition:{tick:"monolith:animation/demo/root/tick",duration:240,priority:10,slot:0}}
function monolith_anim:sequence/define {id:"monolith:demo/orbit",definition:{tick:"monolith:animation/demo/orbit/tick",duration:240,priority:10,slot:0}}
function monolith_anim:sequence/define {id:"monolith:demo/part",definition:{tick:"monolith:animation/demo/part/tick",duration:240,priority:10,slot:0}}
function monolith_anim:sequence/define {id:"monolith:demo/bob",definition:{tick:"monolith:animation/demo/bob/tick",duration:240,priority:10,slot:1}}
function monolith_anim:sequence/define {id:"monolith:demo/hit",definition:{tick:"monolith:animation/demo/hit/tick",duration:20,priority:50,slot:2,on_complete:"monolith:animation/demo/hit/cleanup"}}
function monolith_anim:sequence/define {id:"monolith:demo/recover",definition:{tick:"monolith:animation/demo/recover/tick",duration:40,priority:80,slot:0}}
function monolith_anim:sequence/define {id:"monolith:demo/master",definition:{tick:"monolith:animation/demo/master/tick",duration:241,priority:10,slot:-1}}
function monolith_anim:sequence/define {id:"monolith:demo/entrance",definition:{tick:"monolith:animation/demo/entrance/tick",duration:20,priority:10,slot:0}}
