# Generated by tools/build-animation-debug.mjs
function monolith:animation/demo/reset
function monolith:animation/demo/definitions
execute positioned ^ ^ ^6 summon minecraft:marker run function monolith:animation/demo/create_root
execute as @e[type=minecraft:marker,tag=monolith.anim_demo.root,limit=1] at @s run function monolith:animation/demo/create_children
tellraw @s {text:"Animation hierarchy: Root path + Orbit rotation + Display spin/scale + Bob. Try /function monolith:animation/demo/hit",color:"aqua"}
