# Generated by tools/build-animation-debug.mjs
function monolith:animation/demo/hierarchy
function monolith_anim:parent/select
execute as @e[tag=monolith.anim_demo.root,limit=1] run function monolith_anim:parent/bind {mode:"full_rotation",anchor:"eyes"}
execute as @e[tag=monolith.anim_demo.root,limit=1] run function monolith_anim:node/base {tx:0,ty:0,tz:6000,rx:0,ry:0,rz:0,sx:1000,sy:1000,sz:1000}
