# Generated by tools/build-transform-debug.mjs
function monolith:animation/debug/reset
execute at @s rotated ~ 0 positioned ^0 ^2 ^9 summon minecraft:marker run function monolith:animation/debug/fixture_boss
tellraw @s "BossRoot moves/turns for 10 seconds: core spins, wings extend and scale, crown jumps. Afterward the assembled boss remains. reset removes it."
