# Generated by tools/build-transform-debug.mjs
data merge entity @s {Tags:["monolith.debug","monolith.debug.transform"],block_state:{Name:"minecraft:gold_block"},transformation:{translation:[0f,0f,0f],left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],scale:[0.3f,0.3f,0.3f]},brightness:{block:15,sky:15},teleport_duration:1,interpolation_duration:1}
function monolith:animation/parent/bind {mode:"full_rotation",anchor:"feet"}
function monolith:animation/path/arc {space:"local",sx:-2000,sy:0,sz:0,ex:-4000,ey:0,ez:0,height:500,duration:120,easing:"linear"}
function monolith:animation/start {property:"local_rotation_y",from:0,to:360000,duration:160,easing:"linear"}
function monolith:animation/start {property:"scale_xyz",from:300,to:700,duration:60,easing:"out_back"}
