# Generated by tools/build-transform-debug.mjs
scoreboard players add @s ml_demo_root 1
execute if score @s ml_demo_root matches ..100 run tp @s ~0.025 ~ ~ ~2 ~
execute if score @s ml_demo_root matches 101..200 run tp @s ~-0.025 ~ ~ ~2 ~
execute if score @s ml_demo_root matches 200.. run tag @s remove monolith.debug.boss
