# Generated by tools/build-transform-debug.mjs
execute as @e[tag=monolith.debug.transform] run function monolith:animation/cancel
tellraw @s "Child tweens cancelled at current values; parent following continues."
