# Generated by tools/build-transform-debug.mjs
execute as @e[tag=monolith.debug.transform] run function monolith:animation/parent/unbind
tellraw @s "Children detached, keeping their last pose. Active local tweens continue from that base."
