# Generated by tools/build-transform-debug.mjs
data merge entity @s {Tags:["monolith.debug","monolith.debug.transform"],block_state:{Name:"minecraft:amethyst_block"},transformation:{translation:[0f,0f,0f],left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],scale:[0.3f,0.3f,0.3f]},brightness:{block:15,sky:15},teleport_duration:1,interpolation_duration:1}
function monolith:animation/parent/bind {mode:"full_rotation",anchor:"eyes"}
function monolith:animation/path/bezier {space:"local",sx:2500,sy:1000,sz:3000,ex:2500,ey:1800,ez:4500,cx:4000,cy:3500,cz:2000,duration:120,easing:"in_out_sine"}
function monolith:animation/start {property:"local_rotation_y",from:0,to:720000,duration:120,easing:"linear"}
function monolith:animation/start {property:"scale_xyz",from:300,to:800,duration:60,easing:"out_back"}
