# Generated by tools/build-transform-debug.mjs
data merge entity @s {Tags:["monolith.debug","monolith.debug.transform"],block_state:{Name:"minecraft:white_concrete"},transformation:{translation:[0f,0f,0f],left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],scale:[0.3f,0.3f,0.3f]},brightness:{block:15,sky:15},teleport_duration:1,interpolation_duration:1}
data modify entity @s Rotation set value [90f,0f]
execute store result storage monolith:debug_world x int 1 run data get entity @s Pos[0] 1000
execute store result storage monolith:debug_world y int 1 run data get entity @s Pos[1] 1000
execute store result storage monolith:debug_world z int 1 run data get entity @s Pos[2] 1000
execute store result score @s ml_out_z run data get storage monolith:debug_world z
scoreboard players add @s ml_out_z 5000
execute store result storage monolith:debug_world ez int 1 run scoreboard players get @s ml_out_z
function monolith:animation/debug/world_start with storage monolith:debug_world
function monolith:animation/start {property:"local_rotation_y",from:0,to:360000,duration:100,easing:"linear"}
function monolith:animation/start {property:"scale_xyz",from:300,to:1000,duration:40,easing:"out_back"}
