# Generated by tools/build-transform-debug.mjs
data merge entity @s {Tags:["monolith.debug","monolith.debug.transform"],block_state:{Name:"minecraft:gold_block"},transformation:{translation:[0f,0f,0f],left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],scale:[0.3f,0.3f,0.3f]},brightness:{block:15,sky:15},teleport_duration:1,interpolation_duration:1}
function monolith:animation/path/arc {space:"local",sx:0,sy:0,sz:0,ex:0,ey:0,ez:5000,duration:60,easing:"out_quad",height:2500}
function monolith:animation/start {property:"local_rotation_y",from:0,to:720000,duration:100,easing:"linear"}
function monolith:animation/start {property:"scale_xyz",from:300,to:1000,duration:40,easing:"out_back"}
