# Generated by tools/build-transform-debug.mjs
tag @s add monolith.debug
tag @s add monolith.debug.boss
scoreboard players set @s ml_demo_root 0
function monolith:animation/parent/select
execute summon minecraft:block_display run function monolith:animation/debug/boss_core
execute summon minecraft:block_display run function monolith:animation/debug/boss_left
execute summon minecraft:block_display run function monolith:animation/debug/boss_right
execute summon minecraft:block_display run function monolith:animation/debug/boss_top
