# Generated by tools/build-transform-debug.mjs
function monolith:animation/debug/reset
function monolith:animation/parent/select
execute at @s rotated ~ 0 positioned ^0 ^0 ^0 summon minecraft:block_display run function monolith:animation/debug/fixture_player_position_only
execute at @s rotated ~ 0 positioned ^0 ^0 ^0 summon minecraft:block_display run function monolith:animation/debug/fixture_player_yaw
execute at @s rotated ~ 0 positioned ^0 ^0 ^0 summon minecraft:block_display run function monolith:animation/debug/fixture_player_full_rotation
tellraw @s "Walk and look around: white=position only (feet); gold=yaw (feet); amethyst=full rotation (eyes). Child tweens finish but parent following continues. Use reset to remove."
