# Generated by tools/build-transform-debug.mjs
kill @e[type=minecraft:marker,tag=monolith.debug,tag=monolith.parent]
tellraw @s "BossRoot removed: its children should freeze. reset removes the children."
