# Generated by tools/build-transform-debug.mjs
data merge entity @s {Tags:["monolith.debug","monolith.debug.transform"],block_state:{Name:"minecraft:amethyst_block"},transformation:{translation:[0f,0f,0f],left_rotation:[0f,0f,0f,1f],right_rotation:[0f,0f,0f,1f],scale:[0.3f,0.3f,0.3f]},brightness:{block:15,sky:15},teleport_duration:1,interpolation_duration:1}
tag @s add monolith.sentinel
tag @s add monolith.sentinel.child
tag @s add monolith.sentinel.part1
scoreboard players set @s ml_demo_time 0
function monolith:animation/parent/bind {mode:"full_rotation",anchor:"feet"}
function monolith:animation/path/arc {space:"local",sx:0,sy:0,sz:0,ex:2400,ey:0,ez:0,height:1700,duration:80,easing:"out_quart"}
function monolith:animation/start {property:"local_rotation_z",from:0,to:-720000,duration:80,easing:"linear"}
function monolith:animation/start {property:"scale_xyz",from:0,to:700,duration:36,easing:"out_elastic"}
