# Generated by tools/build-transform-debug.mjs
# Runs after Tween update, so stage transitions start from the completed previous endpoint.
scoreboard players add @s ml_demo_time 1
execute if score @s ml_demo_time matches 80 if entity @s[tag=monolith.sentinel.part0] run function monolith:animation/debug/sentinel_return_0
execute if score @s ml_demo_time matches 80 if entity @s[tag=monolith.sentinel.part1] run function monolith:animation/debug/sentinel_return_1
execute if score @s ml_demo_time matches 80 if entity @s[tag=monolith.sentinel.part2] run function monolith:animation/debug/sentinel_return_2
execute if score @s ml_demo_time matches 80 if entity @s[tag=monolith.sentinel.part3] run function monolith:animation/debug/sentinel_return_3
execute if score @s ml_demo_time matches 80 if entity @s[tag=monolith.sentinel.part4] run function monolith:animation/debug/sentinel_return_4
execute if score @s ml_demo_time matches 120.. run kill @s
