# Generated by tools/build-transform-debug.mjs
# Restart only this sample; other debug fixtures are left alone.
kill @e[tag=monolith.sentinel]
execute at @s rotated ~ 0 positioned ^0 ^2.5 ^8 summon minecraft:marker run function monolith:animation/debug/sentinel_setup
