# Generated by tools/build-transform-debug.mjs
function monolith:animation/path/bezier {space:"local",sx:2400,sy:0,sz:0,cx:0,cy:2600,cz:2400,ex:0,ey:0,ez:0,duration:40,easing:"in_cubic"}
function monolith:animation/start {property:"local_rotation_z",from:-720000,to:-900000,duration:40,easing:"in_quart"}
function monolith:animation/start {property:"scale_xyz",from:700,to:0,duration:40,easing:"in_back"}
