# Generated by tools/build-transform-debug.mjs
scoreboard players add @s ml_demo_time 1
# Move the parent before following children; roll/rotation/scale of parts remain independent.
execute if score @s ml_demo_time matches ..80 run tp @s ~ ~0.008 ~ ~2 ~
execute if score @s ml_demo_time matches 81..120 run tp @s ~ ~-0.016 ~ ~4 ~
execute if score @s ml_demo_time matches 80 run playsound minecraft:block.amethyst_block.chime master @a[distance=..24] ~ ~ ~ 0.8 1.6
execute if score @s ml_demo_time matches 120 run particle minecraft:end_rod ~ ~ ~ 0.25 0.25 0.25 0.1 50
execute if score @s ml_demo_time matches 120 run playsound minecraft:block.beacon.deactivate master @a[distance=..24] ~ ~ ~ 0.5 1.7
# Children reach To and clean up at tick 120; root survives until the following tick.
execute if score @s ml_demo_time matches 121.. run kill @s
