# Generated by tools/build-transform-debug.mjs
tag @s add monolith.debug
tag @s add monolith.sentinel
tag @s add monolith.sentinel.root
scoreboard players set @s ml_demo_time 0
function monolith:animation/parent/select
execute summon minecraft:block_display run function monolith:animation/debug/sentinel_part_0
execute summon minecraft:block_display run function monolith:animation/debug/sentinel_part_1
execute summon minecraft:block_display run function monolith:animation/debug/sentinel_part_2
execute summon minecraft:block_display run function monolith:animation/debug/sentinel_part_3
execute summon minecraft:block_display run function monolith:animation/debug/sentinel_part_4
playsound minecraft:block.amethyst_block.chime master @a[distance=..24] ~ ~ ~ 0.8 0.7
particle minecraft:end_rod ~ ~ ~ 0.15 0.15 0.15 0.02 20
