# Generated by tools/build-transform-debug.mjs
function monolith:animation/debug/reset
execute at @s rotated ~ 0 positioned ^-5 ^2 ^8 summon minecraft:block_display run function monolith:animation/debug/fixture_linear
execute at @s rotated ~ 0 positioned ^0 ^2 ^8 summon minecraft:block_display run function monolith:animation/debug/fixture_arc
execute at @s rotated ~ 0 positioned ^5 ^2 ^8 summon minecraft:block_display run function monolith:animation/debug/fixture_bezier
tellraw @s "Local paths: white=Linear, gold=Arc, amethyst=Bezier. All also rotate and scale independently (3 / 5 / 2 seconds)."
