# Generated by tools/build-transform-debug.mjs
function monolith:animation/debug/reset
execute at @s rotated ~ 0 positioned ^-3 ^2 ^8 summon minecraft:block_display run function monolith:animation/debug/fixture_world
execute at @s rotated ~ 0 positioned ^3 ^2 ^8 summon minecraft:block_display run function monolith:animation/debug/fixture_local
tellraw @s "Both have body yaw=90: white follows world +Z; gold follows local +Z (rotated)."
