# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players operation @s ml_l1syv = @s ml_l1syz
scoreboard players set @s ml_l1sya 0
function monolith_anim:layer/slot/1/refresh
