# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l1sya 1
scoreboard players set @s ml_l1syt 0
scoreboard players operation @s ml_l1syd = @s ml_lc_d
scoreboard players operation @s ml_l1sye = @s ml_le_easing
scoreboard players operation @s ml_l1syf = @s ml_lc_f
scoreboard players operation @s ml_l1syz = @s ml_lc_z
scoreboard players operation @s ml_l1syv = @s ml_lc_f
execute if score @s ml_l1syd matches 0 run function monolith_anim:layer/slot/1/sy/finish
function monolith_anim:layer/slot/1/refresh
