# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l0rza 1
scoreboard players set @s ml_l0rzt 0
scoreboard players operation @s ml_l0rzd = @s ml_lc_d
scoreboard players operation @s ml_l0rze = @s ml_le_easing
scoreboard players operation @s ml_l0rzf = @s ml_lc_f
scoreboard players operation @s ml_l0rzz = @s ml_lc_z
scoreboard players operation @s ml_l0rzv = @s ml_lc_f
execute if score @s ml_l0rzd matches 0 run function monolith_anim:layer/slot/0/rz/finish
function monolith_anim:layer/slot/0/refresh
