# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l3sya 1
scoreboard players set @s ml_l3syt 0
scoreboard players operation @s ml_l3syd = @s ml_lc_d
scoreboard players operation @s ml_l3sye = @s ml_le_easing
scoreboard players operation @s ml_l3syf = @s ml_lc_f
scoreboard players operation @s ml_l3syz = @s ml_lc_z
scoreboard players operation @s ml_l3syv = @s ml_lc_f
execute if score @s ml_l3syd matches 0 run function monolith_anim:layer/slot/3/sy/finish
function monolith_anim:layer/slot/3/refresh
