# Generated by tools/build-animation-layers.mjs
$function monolith_anim:path/start {slot:$(slot),path:2,sx:$(sx),sy:$(sy),sz:$(sz),ex:$(ex),ey:$(ey),ez:$(ez),cx:0,cy:0,cz:0,height:$(height),duration:$(duration),easing:"$(easing)"}
