# Generated by tools/build-animation-layers.mjs
$function monolith_anim:path/start {slot:$(slot),path:3,sx:$(sx),sy:$(sy),sz:$(sz),ex:$(ex),ey:$(ey),ez:$(ez),cx:$(cx),cy:$(cy),cz:$(cz),height:0,duration:$(duration),easing:"$(easing)"}
