# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_ok 0
scoreboard players set @s ml_le_easing -1
$function monolith_anim:easing/resolve/$(easing)
execute unless score @s ml_le_easing matches 0..30 run return 0
$scoreboard players set @s ml_l_slot $(slot)
$scoreboard players set @s ml_lc_path $(path)
$scoreboard players set @s ml_lc_d $(duration)
$scoreboard players set @s ml_lc_h $(height)
execute unless score @s ml_l_slot matches 0..3 run return 0
execute unless score @s ml_lc_path matches 1..3 run return 0
execute unless score @s ml_lc_d matches 0..200000 run return 0
execute unless score @s ml_lc_h matches -1000000..1000000 run return 0
$scoreboard players set @s ml_lc_sx $(sx)
$scoreboard players set @s ml_lc_ex $(ex)
$scoreboard players set @s ml_lc_cx $(cx)
$scoreboard players set @s ml_lc_sy $(sy)
$scoreboard players set @s ml_lc_ey $(ey)
$scoreboard players set @s ml_lc_cy $(cy)
$scoreboard players set @s ml_lc_sz $(sz)
$scoreboard players set @s ml_lc_ez $(ez)
$scoreboard players set @s ml_lc_cz $(cz)
execute unless score @s ml_lc_sx matches -1000000..1000000 run return 0
execute unless score @s ml_lc_ex matches -1000000..1000000 run return 0
execute unless score @s ml_lc_cx matches -1000000..1000000 run return 0
execute unless score @s ml_lc_sy matches -1000000..1000000 run return 0
execute unless score @s ml_lc_ey matches -1000000..1000000 run return 0
execute unless score @s ml_lc_cy matches -1000000..1000000 run return 0
execute unless score @s ml_lc_sz matches -1000000..1000000 run return 0
execute unless score @s ml_lc_ez matches -1000000..1000000 run return 0
execute unless score @s ml_lc_cz matches -1000000..1000000 run return 0
function monolith_anim:layer/init
execute if score @s ml_l_slot matches 0 run function monolith_anim:path/slot/0/start
execute if score @s ml_l_slot matches 1 run function monolith_anim:path/slot/1/start
execute if score @s ml_l_slot matches 2 run function monolith_anim:path/slot/2/start
execute if score @s ml_l_slot matches 3 run function monolith_anim:path/slot/3/start
function monolith_anim:layer/compose
return 1
