# Generated by tools/build-transform.mjs
function monolith:animation/track/t/load
function monolith:animation/value/finish
function monolith:animation/track/t/save
scoreboard players set @s ml_t_active 0
