# Generated by tools/build-transform.mjs
scoreboard players operation @s ml_a_elapsed = @s ml_t_elapsed
scoreboard players operation @s ml_a_duration = @s ml_t_duration
scoreboard players operation @s ml_a_easing = @s ml_t_easing
scoreboard players operation @s ml_a_from = @s ml_t_from
scoreboard players operation @s ml_a_to = @s ml_t_to
scoreboard players operation @s ml_a_property = @s ml_t_property
