# Generated by tools/build-transform.mjs
scoreboard players operation @s ml_t_elapsed = @s ml_a_elapsed
scoreboard players operation @s ml_t_duration = @s ml_a_duration
scoreboard players operation @s ml_t_easing = @s ml_a_easing
scoreboard players operation @s ml_t_from = @s ml_a_from
scoreboard players operation @s ml_t_to = @s ml_a_to
scoreboard players operation @s ml_t_property = @s ml_a_property
