# Generated by tools/build-transform.mjs
scoreboard players set @s ml_t_active 1
function monolith:animation/track/t/save
scoreboard players operation @s ml_a_value = @s ml_a_from
function monolith:animation/adapter/dispatch
execute if score @s ml_a_duration matches ..0 run function monolith:animation/value/finish
execute if score @s ml_a_duration matches ..0 run scoreboard players set @s ml_t_active 0
function monolith:animation/track/t/save
function monolith:animation/track/refresh
