# Generated by tools/build-transform.mjs
function monolith:animation/track/t/load
function monolith:animation/value/update
function monolith:animation/track/t/save
execute if score @s ml_a_duration matches ..0 run scoreboard players set @s ml_t_active 0
