# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players operation @s ml_l3sxv = @s ml_l3sxz
scoreboard players set @s ml_l3sxa 0
function monolith_anim:layer/slot/3/refresh
