# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l3sxa 1
scoreboard players set @s ml_l3sxt 0
scoreboard players operation @s ml_l3sxd = @s ml_lc_d
scoreboard players operation @s ml_l3sxe = @s ml_le_easing
scoreboard players operation @s ml_l3sxf = @s ml_lc_f
scoreboard players operation @s ml_l3sxz = @s ml_lc_z
scoreboard players operation @s ml_l3sxv = @s ml_lc_f
execute if score @s ml_l3sxd matches 0 run function monolith_anim:layer/slot/3/sx/finish
function monolith_anim:layer/slot/3/refresh
