# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players add @s ml_l3sxt 1
execute if score @s ml_l3sxt >= @s ml_l3sxd run return run function monolith_anim:layer/slot/3/sx/finish
scoreboard players operation @s ml_le_tmp0 = @s ml_l3sxt
scoreboard players operation @s ml_le_tmp0 *= #scale ml_le_tmp0
scoreboard players operation @s ml_le_tmp0 /= @s ml_l3sxd
scoreboard players operation @s ml_le_easing = @s ml_l3sxe
function monolith_anim:easing/dispatch
scoreboard players operation @s ml_lm_u = @s ml_le_tmp1
scoreboard players operation @s ml_lm_a = @s ml_l3sxf
scoreboard players operation @s ml_lm_b = @s ml_l3sxz
function monolith_anim:math/layer_lerp
scoreboard players operation @s ml_l3sxv = @s ml_lm_v
