# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l2rxa 1
scoreboard players set @s ml_l2rxt 0
scoreboard players operation @s ml_l2rxd = @s ml_lc_d
scoreboard players operation @s ml_l2rxe = @s ml_le_easing
scoreboard players operation @s ml_l2rxf = @s ml_lc_f
scoreboard players operation @s ml_l2rxz = @s ml_lc_z
scoreboard players operation @s ml_l2rxv = @s ml_lc_f
execute if score @s ml_l2rxd matches 0 run function monolith_anim:layer/slot/2/rx/finish
function monolith_anim:layer/slot/2/refresh
