# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players add @s ml_l2rxt 1
execute if score @s ml_l2rxt >= @s ml_l2rxd run return run function monolith_anim:layer/slot/2/rx/finish
scoreboard players operation @s ml_le_tmp0 = @s ml_l2rxt
scoreboard players operation @s ml_le_tmp0 *= #scale ml_le_tmp0
scoreboard players operation @s ml_le_tmp0 /= @s ml_l2rxd
scoreboard players operation @s ml_le_easing = @s ml_l2rxe
function monolith_anim:easing/dispatch
scoreboard players operation @s ml_lm_u = @s ml_le_tmp1
scoreboard players operation @s ml_lm_a = @s ml_l2rxf
scoreboard players operation @s ml_lm_b = @s ml_l2rxz
function monolith_anim:math/layer_lerp
scoreboard players operation @s ml_l2rxv = @s ml_lm_v
