# Generated by tools/build-animation-debug.mjs
execute if score @s ml_seq_time matches 0 run function monolith_anim:layer/start {slot:0,property:"rotation_y",from:0,to:720000,duration:240,easing:"linear"}
execute if score @s ml_seq_time matches 0 run function monolith_anim:layer/start {slot:0,property:"rotation_z",from:0,to:25000,duration:120,easing:"in_out_sine"}
execute if score @s ml_seq_time matches 120 run function monolith_anim:layer/start {slot:0,property:"rotation_z",from:25000,to:0,duration:120,easing:"in_out_sine"}
