# Generated by tools/build-animation-debug.mjs
# Independent XYZ rotations and scale channels share layer 0.
execute if score @s ml_seq_time matches 0 run function monolith_anim:layer/start {slot:0,property:"rotation_x",from:0,to:360000,duration:240,easing:"linear"}
execute if score @s ml_seq_time matches 0 run function monolith_anim:layer/start {slot:0,property:"rotation_y",from:0,to:720000,duration:240,easing:"linear"}
execute if score @s ml_seq_time matches 0 run function monolith_anim:layer/start {slot:0,property:"rotation_z",from:0,to:180000,duration:160,easing:"linear"}
execute if score @s ml_seq_time matches 0 run function monolith_anim:layer/start {slot:0,property:"scale_y",from:1000,to:2500,duration:60,easing:"out_back"}
execute if score @s ml_seq_time matches 60 run function monolith_anim:layer/start {slot:0,property:"scale_y",from:2500,to:1000,duration:60,easing:"in_out_sine"}
execute if score @s ml_seq_time matches 120 run function monolith_anim:layer/start {slot:0,property:"scale_x",from:1000,to:1800,duration:60,easing:"out_quad"}
execute if score @s ml_seq_time matches 180 run function monolith_anim:layer/start {slot:0,property:"scale_x",from:1800,to:1000,duration:60,easing:"in_out_sine"}
