# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l1sza 1
scoreboard players set @s ml_l1szt 0
scoreboard players operation @s ml_l1szd = @s ml_lc_d
scoreboard players operation @s ml_l1sze = @s ml_le_easing
scoreboard players operation @s ml_l1szf = @s ml_lc_f
scoreboard players operation @s ml_l1szz = @s ml_lc_z
scoreboard players operation @s ml_l1szv = @s ml_lc_f
execute if score @s ml_l1szd matches 0 run function monolith_anim:layer/slot/1/sz/finish
function monolith_anim:layer/slot/1/refresh
