# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l1_path 0
scoreboard players set @s ml_l1tya 1
scoreboard players set @s ml_l1tyt 0
scoreboard players operation @s ml_l1tyd = @s ml_lc_d
scoreboard players operation @s ml_l1tye = @s ml_le_easing
scoreboard players operation @s ml_l1tyf = @s ml_lc_f
scoreboard players operation @s ml_l1tyz = @s ml_lc_z
scoreboard players operation @s ml_l1tyv = @s ml_lc_f
execute if score @s ml_l1tyd matches 0 run function monolith_anim:layer/slot/1/ty/finish
function monolith_anim:layer/slot/1/refresh
