# Generated by tools/build-transform.mjs
function monolith:animation/rotation/prepare
# Assign all quaternion components: never retain a component from the previous axis.
data modify entity @s transformation.left_rotation[0] set value 0f
data modify entity @s transformation.left_rotation[1] set value 0f
execute store result entity @s transformation.left_rotation[2] float 0.0001 run scoreboard players get @s ml_rot_s0
execute store result entity @s transformation.left_rotation[3] float 0.0001 run scoreboard players get @s ml_rot_c0
