# Generated by tools/build-transform.mjs
execute if entity @s[tag=monolith.child] run return run function monolith:animation/adapter/local_rotation_y
execute store result entity @s Rotation[0] float 0.001 run scoreboard players get @s ml_a_value
