# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l0_path 0
scoreboard players set @s ml_l0txa 1
scoreboard players set @s ml_l0txt 0
scoreboard players operation @s ml_l0txd = @s ml_lc_d
scoreboard players operation @s ml_l0txe = @s ml_le_easing
scoreboard players operation @s ml_l0txf = @s ml_lc_f
scoreboard players operation @s ml_l0txz = @s ml_lc_z
scoreboard players operation @s ml_l0txv = @s ml_lc_f
execute if score @s ml_l0txd matches 0 run function monolith_anim:layer/slot/0/tx/finish
function monolith_anim:layer/slot/0/refresh
