# Generated by tools/build-transform.mjs
scoreboard players operation @s ml_a_value = @s ml_a_to
function monolith:animation/adapter/dispatch
scoreboard players set @s ml_a_elapsed 0
scoreboard players set @s ml_a_duration 0
