# Generated by tools/build-transform.mjs
execute if score @s ml_a_duration matches ..0 run return run function monolith:animation/value/finish
scoreboard players add @s ml_a_elapsed 1
execute if score @s ml_a_elapsed >= @s ml_a_duration run return run function monolith:animation/value/finish
scoreboard players operation @s ml_a_tmp0 = @s ml_a_elapsed
scoreboard players operation @s ml_a_tmp0 *= #scale ml_a_tmp0
scoreboard players operation @s ml_a_tmp0 /= @s ml_a_duration
function monolith:animation/easing/dispatch
scoreboard players operation @s ml_path_u = @s ml_a_tmp1
scoreboard players operation @s ml_path_a = @s ml_a_from
scoreboard players operation @s ml_path_b = @s ml_a_to
function monolith:animation/math/lerp
scoreboard players operation @s ml_a_value = @s ml_path_v
function monolith:animation/adapter/dispatch
