# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l1rya 1
scoreboard players set @s ml_l1ryt 0
scoreboard players operation @s ml_l1ryd = @s ml_lc_d
scoreboard players operation @s ml_l1rye = @s ml_le_easing
scoreboard players operation @s ml_l1ryf = @s ml_lc_f
scoreboard players operation @s ml_l1ryz = @s ml_lc_z
scoreboard players operation @s ml_l1ryv = @s ml_lc_f
execute if score @s ml_l1ryd matches 0 run function monolith_anim:layer/slot/1/ry/finish
function monolith_anim:layer/slot/1/refresh
