# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l2_path 0
scoreboard players set @s ml_l2tya 1
scoreboard players set @s ml_l2tyt 0
scoreboard players operation @s ml_l2tyd = @s ml_lc_d
scoreboard players operation @s ml_l2tye = @s ml_le_easing
scoreboard players operation @s ml_l2tyf = @s ml_lc_f
scoreboard players operation @s ml_l2tyz = @s ml_lc_z
scoreboard players operation @s ml_l2tyv = @s ml_lc_f
execute if score @s ml_l2tyd matches 0 run function monolith_anim:layer/slot/2/ty/finish
function monolith_anim:layer/slot/2/refresh
