# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l0rya 1
scoreboard players set @s ml_l0ryt 0
scoreboard players operation @s ml_l0ryd = @s ml_lc_d
scoreboard players operation @s ml_l0rye = @s ml_le_easing
scoreboard players operation @s ml_l0ryf = @s ml_lc_f
scoreboard players operation @s ml_l0ryz = @s ml_lc_z
scoreboard players operation @s ml_l0ryv = @s ml_lc_f
execute if score @s ml_l0ryd matches 0 run function monolith_anim:layer/slot/0/ry/finish
function monolith_anim:layer/slot/0/refresh
