# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l3_path 0
scoreboard players set @s ml_l3tza 1
scoreboard players set @s ml_l3tzt 0
scoreboard players operation @s ml_l3tzd = @s ml_lc_d
scoreboard players operation @s ml_l3tze = @s ml_le_easing
scoreboard players operation @s ml_l3tzf = @s ml_lc_f
scoreboard players operation @s ml_l3tzz = @s ml_lc_z
scoreboard players operation @s ml_l3tzv = @s ml_lc_f
execute if score @s ml_l3tzd matches 0 run function monolith_anim:layer/slot/3/tz/finish
function monolith_anim:layer/slot/3/refresh
