# Generated by tools/build-transform.mjs
function monolith:animation/track/s/load
function monolith:animation/value/finish
function monolith:animation/track/s/save
scoreboard players set @s ml_s_active 0
