# Generated by tools/build-transform.mjs
scoreboard players operation @s ml_a_elapsed = @s ml_s_elapsed
scoreboard players operation @s ml_a_duration = @s ml_s_duration
scoreboard players operation @s ml_a_easing = @s ml_s_easing
scoreboard players operation @s ml_a_from = @s ml_s_from
scoreboard players operation @s ml_a_to = @s ml_s_to
scoreboard players operation @s ml_a_property = @s ml_s_property
