# Generated by tools/build-transform.mjs
scoreboard players operation @s ml_s_elapsed = @s ml_a_elapsed
scoreboard players operation @s ml_s_duration = @s ml_a_duration
scoreboard players operation @s ml_s_easing = @s ml_a_easing
scoreboard players operation @s ml_s_from = @s ml_a_from
scoreboard players operation @s ml_s_to = @s ml_a_to
scoreboard players operation @s ml_s_property = @s ml_a_property
