# Generated by tools/build-transform.mjs
$function monolith:animation/path/start {space:"$(space)",path:1,sx:$(sx),sy:$(sy),sz:$(sz),ex:$(ex),ey:$(ey),ez:$(ez),cx:0,cy:0,cz:0,height:$(height),duration:$(duration),easing:"$(easing)"}
