# Generated by tools/build-transform.mjs
scoreboard players operation @s ml_path_h = @s ml_path_u
scoreboard players operation @s ml_path_h *= @s ml_path_u
scoreboard players operation @s ml_path_h /= #scale ml_a_tmp0
scoreboard players operation @s ml_path_a = @s ml_path_u
scoreboard players operation @s ml_path_a -= @s ml_path_h
scoreboard players operation @s ml_path_a *= #four ml_a_tmp0
scoreboard players operation @s ml_path_h = @s ml_path_u
scoreboard players operation @s ml_path_u = @s ml_path_a
scoreboard players set @s ml_path_a 0
scoreboard players operation @s ml_path_b = @s ml_height
function monolith:animation/math/lerp
scoreboard players operation @s ml_out_y += @s ml_path_v
scoreboard players operation @s ml_path_u = @s ml_path_h
