# Generated by tools/build-transform.mjs
scoreboard players operation @s ml_path_a = @s ml_start_z
scoreboard players operation @s ml_path_b = @s ml_end_z
execute if score @s ml_path_type matches 2 run scoreboard players operation @s ml_path_b = @s ml_ctrl_z
function monolith:animation/math/lerp
scoreboard players operation @s ml_out_z = @s ml_path_v
execute if score @s ml_path_type matches 2 run function monolith:animation/path/bezier_z
