# Generated by tools/build-transform.mjs
scoreboard players operation @s ml_path_a = @s ml_start_x
scoreboard players operation @s ml_path_b = @s ml_end_x
execute if score @s ml_path_type matches 2 run scoreboard players operation @s ml_path_b = @s ml_ctrl_x
function monolith:animation/math/lerp
scoreboard players operation @s ml_out_x = @s ml_path_v
execute if score @s ml_path_type matches 2 run function monolith:animation/path/bezier_x
