# Generated by tools/build-transform.mjs
$function monolith:animation/path/start {space:"$(space)",path:2,sx:$(sx),sy:$(sy),sz:$(sz),ex:$(ex),ey:$(ey),ez:$(ez),cx:$(cx),cy:$(cy),cz:$(cz),height:0,duration:$(duration),easing:"$(easing)"}
