# Generated by tools/build-transform.mjs
scoreboard players operation @s ml_path_a = @s ml_ctrl_z
scoreboard players operation @s ml_path_b = @s ml_end_z
function monolith:animation/math/lerp
scoreboard players operation @s ml_path_b = @s ml_path_v
scoreboard players operation @s ml_path_a = @s ml_out_z
function monolith:animation/math/lerp
scoreboard players operation @s ml_out_z = @s ml_path_v
