# Generated by tools/build-transform.mjs
# ml_a_value is eased progress, deliberately not clamped (Back/Elastic overshoot).
scoreboard players operation @s ml_path_u = @s ml_a_value
function monolith:animation/path/axis_x
function monolith:animation/path/axis_y
function monolith:animation/path/axis_z
execute if score @s ml_path_type matches 1 run function monolith:animation/path/arc_height
execute unless score @s ml_space matches 1 store result entity @s transformation.translation[0] float 0.001 run scoreboard players get @s ml_out_x
execute if score @s ml_space matches 1 store result entity @s Pos[0] double 0.001 run scoreboard players get @s ml_out_x
execute unless score @s ml_space matches 1 store result entity @s transformation.translation[1] float 0.001 run scoreboard players get @s ml_out_y
execute if score @s ml_space matches 1 store result entity @s Pos[1] double 0.001 run scoreboard players get @s ml_out_y
execute unless score @s ml_space matches 1 store result entity @s transformation.translation[2] float 0.001 run scoreboard players get @s ml_out_z
execute if score @s ml_space matches 1 store result entity @s Pos[2] double 0.001 run scoreboard players get @s ml_out_z
