# Generated by tools/build-transform.mjs
execute if entity @s[tag=monolith_anim.node] run return 0
execute unless entity @s[type=minecraft:block_display] unless entity @s[type=minecraft:item_display] unless entity @s[type=minecraft:text_display] run return 0
scoreboard players set @s ml_a_easing -1
scoreboard players set @s ml_cfg_space -1
$function monolith:animation/easing/resolve/$(easing)
$function monolith:animation/path/space/$(space)
execute unless score @s ml_a_easing matches 0..30 run return 0
execute unless score @s ml_cfg_space matches 0..1 run return 0
$scoreboard players set @s ml_cfg_path $(path)
$scoreboard players set @s ml_cfg_height $(height)
$scoreboard players set @s ml_a_duration $(duration)
execute unless score @s ml_cfg_path matches 0..2 run return 0
execute unless score @s ml_cfg_height matches -100000..100000 run return 0
execute if score @s ml_a_duration matches 200001.. run return 0
$scoreboard players set @s ml_cfgs_x $(sx)
$scoreboard players set @s ml_cfge_x $(ex)
$scoreboard players set @s ml_cfgc_x $(cx)
$scoreboard players set @s ml_cfgs_y $(sy)
$scoreboard players set @s ml_cfge_y $(ey)
$scoreboard players set @s ml_cfgc_y $(cy)
$scoreboard players set @s ml_cfgs_z $(sz)
$scoreboard players set @s ml_cfge_z $(ez)
$scoreboard players set @s ml_cfgc_z $(cz)
execute unless score @s ml_cfgs_x matches -100000000..100000000 run return 0
execute unless score @s ml_cfge_x matches -100000000..100000000 run return 0
execute unless score @s ml_cfgc_x matches -100000000..100000000 run return 0
execute unless score @s ml_cfgs_y matches -100000000..100000000 run return 0
execute unless score @s ml_cfge_y matches -100000000..100000000 run return 0
execute unless score @s ml_cfgc_y matches -100000000..100000000 run return 0
execute unless score @s ml_cfgs_z matches -100000000..100000000 run return 0
execute unless score @s ml_cfge_z matches -100000000..100000000 run return 0
execute unless score @s ml_cfgc_z matches -100000000..100000000 run return 0
scoreboard players operation @s ml_start_x = @s ml_cfgs_x
scoreboard players operation @s ml_end_x = @s ml_cfge_x
scoreboard players operation @s ml_ctrl_x = @s ml_cfgc_x
scoreboard players operation @s ml_start_y = @s ml_cfgs_y
scoreboard players operation @s ml_end_y = @s ml_cfge_y
scoreboard players operation @s ml_ctrl_y = @s ml_cfgc_y
scoreboard players operation @s ml_start_z = @s ml_cfgs_z
scoreboard players operation @s ml_end_z = @s ml_cfge_z
scoreboard players operation @s ml_ctrl_z = @s ml_cfgc_z
scoreboard players operation @s ml_space = @s ml_cfg_space
scoreboard players operation @s ml_path_type = @s ml_cfg_path
scoreboard players operation @s ml_height = @s ml_cfg_height
execute if score @s ml_space matches 1 run data modify entity @s transformation.translation set value [0f,0f,0f]
scoreboard players set @s ml_a_property 9
scoreboard players set @s ml_a_from 0
scoreboard players set @s ml_a_to 10000
scoreboard players set @s ml_a_elapsed 0
function monolith:animation/track/t/start
