# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players operation @s ml_l2tzv = @s ml_l2tzz
scoreboard players set @s ml_l2tza 0
function monolith_anim:layer/slot/2/refresh
