# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l2_path 0
scoreboard players set @s ml_l2tza 1
scoreboard players set @s ml_l2tzt 0
scoreboard players operation @s ml_l2tzd = @s ml_lc_d
scoreboard players operation @s ml_l2tze = @s ml_le_easing
scoreboard players operation @s ml_l2tzf = @s ml_lc_f
scoreboard players operation @s ml_l2tzz = @s ml_lc_z
scoreboard players operation @s ml_l2tzv = @s ml_lc_f
execute if score @s ml_l2tzd matches 0 run function monolith_anim:layer/slot/2/tz/finish
function monolith_anim:layer/slot/2/refresh
