# Generated by tools/build-transform.mjs
function monolith:animation/track/r/load
function monolith:animation/value/finish
function monolith:animation/track/r/save
scoreboard players set @s ml_r_active 0
