# Generated by tools/build-transform.mjs
function monolith:animation/track/r/load
function monolith:animation/value/update
function monolith:animation/track/r/save
execute if score @s ml_a_duration matches ..0 run scoreboard players set @s ml_r_active 0
