# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players operation @s ml_l0rxv = @s ml_l0rxz
scoreboard players set @s ml_l0rxa 0
function monolith_anim:layer/slot/0/refresh
