# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l0rxa 1
scoreboard players set @s ml_l0rxt 0
scoreboard players operation @s ml_l0rxd = @s ml_lc_d
scoreboard players operation @s ml_l0rxe = @s ml_le_easing
scoreboard players operation @s ml_l0rxf = @s ml_lc_f
scoreboard players operation @s ml_l0rxz = @s ml_lc_z
scoreboard players operation @s ml_l0rxv = @s ml_lc_f
execute if score @s ml_l0rxd matches 0 run function monolith_anim:layer/slot/0/rx/finish
function monolith_anim:layer/slot/0/refresh
