# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players add @s ml_l0rxt 1
execute if score @s ml_l0rxt >= @s ml_l0rxd run return run function monolith_anim:layer/slot/0/rx/finish
scoreboard players operation @s ml_le_tmp0 = @s ml_l0rxt
scoreboard players operation @s ml_le_tmp0 *= #scale ml_le_tmp0
scoreboard players operation @s ml_le_tmp0 /= @s ml_l0rxd
scoreboard players operation @s ml_le_easing = @s ml_l0rxe
function monolith_anim:easing/dispatch
scoreboard players operation @s ml_lm_u = @s ml_le_tmp1
scoreboard players operation @s ml_lm_a = @s ml_l0rxf
scoreboard players operation @s ml_lm_b = @s ml_l0rxz
function monolith_anim:math/layer_lerp
scoreboard players operation @s ml_l0rxv = @s ml_lm_v
