# Generated by tools/build-animation-layers.mjs
scoreboard players operation @s ml_lm_w = @s ml_lm_b
scoreboard players operation @s ml_lm_w -= @s ml_lm_a
scoreboard players operation @s ml_lm_v = @s ml_lm_w
scoreboard players operation @s ml_lm_v /= #scale ml_le_tmp0
scoreboard players operation @s ml_lm_v *= @s ml_lm_u
scoreboard players operation @s ml_lm_w %= #scale ml_le_tmp0
scoreboard players operation @s ml_lm_w *= @s ml_lm_u
scoreboard players operation @s ml_lm_w /= #scale ml_le_tmp0
scoreboard players operation @s ml_lm_v += @s ml_lm_w
scoreboard players operation @s ml_lm_v += @s ml_lm_a
