# Generated by tools/build-animation-layers.mjs
execute if score @s ml_le_tmp0 matches ..4999 run return run function monolith_anim:easing/in_out_quint_first
execute if score @s ml_le_tmp0 matches 5000.. run function monolith_anim:easing/in_out_quint_second
