# Generated by tools/build-animation-layers.mjs
scoreboard players operation @s ml_le_tmp0 -= #scale ml_le_tmp0
scoreboard players operation @s ml_le_tmp0 *= #two ml_le_tmp0
function monolith_anim:easing/in_quart
scoreboard players operation @s ml_le_tmp1 /= #two ml_le_tmp0
scoreboard players operation @s ml_le_tmp0 = #scale ml_le_tmp0
scoreboard players operation @s ml_le_tmp0 -= @s ml_le_tmp1
scoreboard players operation @s ml_le_tmp1 = @s ml_le_tmp0
