# Generated by tools/build-animation-layers.mjs
execute if score @s ml_le_tmp0 matches ..3636 run function monolith_anim:easing/out_bounce_1
execute if score @s ml_le_tmp0 matches 3637..7272 run function monolith_anim:easing/out_bounce_2
execute if score @s ml_le_tmp0 matches 7273..9090 run function monolith_anim:easing/out_bounce_3
execute if score @s ml_le_tmp0 matches 9091.. run function monolith_anim:easing/out_bounce_4
