# Generated by tools/build-animation-layers.mjs
scoreboard players operation @s ml_le_tmp1 = @s ml_le_tmp0
scoreboard players operation @s ml_le_tmp0 = #scale ml_le_tmp0
scoreboard players operation @s ml_le_tmp0 -= @s ml_le_tmp1
function monolith_anim:easing/in_quint
scoreboard players operation @s ml_le_tmp0 = #scale ml_le_tmp0
scoreboard players operation @s ml_le_tmp0 -= @s ml_le_tmp1
scoreboard players operation @s ml_le_tmp1 = @s ml_le_tmp0
