# Generated by tools/build-animation-layers.mjs
function monolith_anim:easing/lut/prepare
execute if score @s ml_le_lut_i matches 40.. run scoreboard players set @s ml_le_tmp1 10000
execute unless score @s ml_le_lut_i matches 40.. run function monolith_anim:easing/lut/sample/out_sine
