# Generated by tools/build-animation-layers.mjs
scoreboard players operation @s ml_le_tmp0 -= #scale ml_le_tmp0
scoreboard players operation @s ml_le_tmp1 = @s ml_le_tmp0
scoreboard players operation @s ml_le_tmp1 *= @s ml_le_tmp0
scoreboard players operation @s ml_le_tmp1 /= #scale ml_le_tmp0
scoreboard players operation @s ml_le_tmp0 *= @s ml_le_tmp1
scoreboard players operation @s ml_le_tmp0 /= #scale ml_le_tmp0
scoreboard players operation @s ml_le_tmp0 *= #back_c3 ml_le_tmp0
scoreboard players operation @s ml_le_tmp0 /= #scale ml_le_tmp0
scoreboard players operation @s ml_le_tmp1 *= #back_c1 ml_le_tmp0
scoreboard players operation @s ml_le_tmp1 /= #scale ml_le_tmp0
scoreboard players operation @s ml_le_tmp1 += @s ml_le_tmp0
scoreboard players operation @s ml_le_tmp1 += #scale ml_le_tmp0
