# Generated by tools/build-transform.mjs
scoreboard players set @s ml_t_active 0
scoreboard players set @s ml_r_active 0
scoreboard players set @s ml_s_active 0
execute if score @s ml_a_property matches 0..2 run function monolith:animation/track/t/save
execute if score @s ml_a_property matches 0..2 run scoreboard players set @s ml_t_active 1
execute if score @s ml_a_property matches 3..6 run function monolith:animation/track/s/save
execute if score @s ml_a_property matches 3..6 run scoreboard players set @s ml_s_active 1
execute if score @s ml_a_property matches 7..8 run function monolith:animation/track/r/save
execute if score @s ml_a_property matches 7..8 run scoreboard players set @s ml_r_active 1
