# Generated by tools/build-transform.mjs
tag @s remove monolith.animating
execute if score @s ml_t_active matches 1 run tag @s add monolith.animating
execute if score @s ml_r_active matches 1 run tag @s add monolith.animating
execute if score @s ml_s_active matches 1 run tag @s add monolith.animating
