# Generated by tools/build-animation-sequence.mjs
execute store result score #slot ma_sq_tmp run data get storage monolith_anim:sequence requests[-1].definition.slot
execute if score #slot ma_sq_tmp matches 0 if score @s ml_sq_slot0 matches 1.. run return 0
execute if score #slot ma_sq_tmp matches 1 if score @s ml_sq_slot1 matches 1.. run return 0
execute if score #slot ma_sq_tmp matches 2 if score @s ml_sq_slot2 matches 1.. run return 0
execute if score #slot ma_sq_tmp matches 3 if score @s ml_sq_slot3 matches 1.. run return 0
$execute if score #slot ma_sq_tmp matches 0 run scoreboard players set @s ml_sq_slot0 $(instance)
$execute if score #slot ma_sq_tmp matches 1 run scoreboard players set @s ml_sq_slot1 $(instance)
$execute if score #slot ma_sq_tmp matches 2 run scoreboard players set @s ml_sq_slot2 $(instance)
$execute if score #slot ma_sq_tmp matches 3 run scoreboard players set @s ml_sq_slot3 $(instance)
$scoreboard players set @e[type=minecraft:marker,tag=monolith_anim.sequence,scores={ma_si_id=$(instance)},limit=1] ma_sq_live 1
$data modify storage monolith_anim:sequence requests[-1].result set value $(instance)
