# Generated by tools/build-animation-sequence.mjs
execute unless score @s ma_sq_live matches 1 run return 0
execute unless score @s ma_sq_dead matches 0 run return 0
execute unless score @s ma_sq_block matches 0 run return 0
$scoreboard players set @s ma_sq_block $(instance)
function monolith_anim:sequence/internal/freeze
