# Generated by tools/build-animation-sequence.mjs
execute unless score @s ma_sq_dead matches 0 run return 0
scoreboard players set @s ma_sq_dead 2
tag @s remove monolith_anim.sequence_step
function monolith_anim:sequence/internal/event_cancel
function monolith_anim:sequence/internal/cleanup
