# Generated by tools/build-animation-sequence.mjs
data modify storage monolith_anim:sequence claim set value {instance:0}
execute store result storage monolith_anim:sequence claim.instance int 1 run scoreboard players get @s ml_sq_slot2
function monolith_anim:sequence/internal/check_claim_macro_2 with storage monolith_anim:sequence claim
