# Generated by tools/build-animation-sequence.mjs
$execute unless entity @e[type=minecraft:marker,tag=monolith_anim.sequence,scores={ma_si_id=$(instance)},limit=1] run scoreboard players set @s ml_sq_slot3 0
