# Generated by tools/build-animation-sequence.mjs
$execute unless entity @e[tag=monolith_anim.owner,scores={ma_so_id=$(owner)},limit=1] run return run function monolith_anim:sequence/internal/cancel
$execute at @e[tag=monolith_anim.owner,scores={ma_so_id=$(owner)},limit=1] run tp @s ~ ~ ~
