# Generated by tools/build-animation-sequence.mjs
data modify storage monolith_anim:sequence probe set value {owner:0}
execute store result storage monolith_anim:sequence probe.owner int 1 run scoreboard players get @s ma_so_id
function monolith_anim:sequence/internal/check_owner_macro with storage monolith_anim:sequence probe
