# Generated by tools/build-animation-sequence.mjs
scoreboard players set #denied ma_sq_tmp 0
execute if score #slot ma_sq_tmp matches 0 if score @s ml_sq_slot0 matches 1.. run scoreboard players set #denied ma_sq_tmp 1
execute if data storage monolith_anim:sequence requests[-1]{api:"interrupt",mode:"cancel"} run scoreboard players set #denied ma_sq_tmp 0
execute if data storage monolith_anim:sequence requests[-1]{api:"interrupt",mode:"replace"} run scoreboard players set #denied ma_sq_tmp 0
$execute if data storage monolith_anim:sequence requests[-1]{api:"child",mode:"replace"} if score #slot ma_sq_tmp matches 0 if score @s ml_sq_slot0 matches $(parent) run scoreboard players set #denied ma_sq_tmp 0
execute if score #slot ma_sq_tmp matches 1 if score @s ml_sq_slot1 matches 1.. run scoreboard players set #denied ma_sq_tmp 1
execute if data storage monolith_anim:sequence requests[-1]{api:"interrupt",mode:"cancel"} run scoreboard players set #denied ma_sq_tmp 0
execute if data storage monolith_anim:sequence requests[-1]{api:"interrupt",mode:"replace"} run scoreboard players set #denied ma_sq_tmp 0
$execute if data storage monolith_anim:sequence requests[-1]{api:"child",mode:"replace"} if score #slot ma_sq_tmp matches 1 if score @s ml_sq_slot1 matches $(parent) run scoreboard players set #denied ma_sq_tmp 0
execute if score #slot ma_sq_tmp matches 2 if score @s ml_sq_slot2 matches 1.. run scoreboard players set #denied ma_sq_tmp 1
execute if data storage monolith_anim:sequence requests[-1]{api:"interrupt",mode:"cancel"} run scoreboard players set #denied ma_sq_tmp 0
execute if data storage monolith_anim:sequence requests[-1]{api:"interrupt",mode:"replace"} run scoreboard players set #denied ma_sq_tmp 0
$execute if data storage monolith_anim:sequence requests[-1]{api:"child",mode:"replace"} if score #slot ma_sq_tmp matches 2 if score @s ml_sq_slot2 matches $(parent) run scoreboard players set #denied ma_sq_tmp 0
execute if score #slot ma_sq_tmp matches 3 if score @s ml_sq_slot3 matches 1.. run scoreboard players set #denied ma_sq_tmp 1
execute if data storage monolith_anim:sequence requests[-1]{api:"interrupt",mode:"cancel"} run scoreboard players set #denied ma_sq_tmp 0
execute if data storage monolith_anim:sequence requests[-1]{api:"interrupt",mode:"replace"} run scoreboard players set #denied ma_sq_tmp 0
$execute if data storage monolith_anim:sequence requests[-1]{api:"child",mode:"replace"} if score #slot ma_sq_tmp matches 3 if score @s ml_sq_slot3 matches $(parent) run scoreboard players set #denied ma_sq_tmp 0
