# Generated by tools/build-animation-sequence.mjs
data modify storage monolith_anim:sequence cleanup_frames append value {instance:0}
execute store result storage monolith_anim:sequence cleanup_frames[-1].instance int 1 run scoreboard players get @s ma_si_id
function monolith_anim:sequence/internal/release_waiters with storage monolith_anim:sequence cleanup_frames[-1]
data remove storage monolith_anim:sequence cleanup_frames[-1]
kill @s
