# Generated by tools/build-animation-sequence.mjs
# External control requires owner execution and the returned instance ID.
$execute as @e[type=minecraft:marker,tag=monolith_anim.sequence,scores={ma_si_id=$(instance),ma_sq_live=1,ma_sq_dead=0},limit=1] if score @s ma_so_id = #control_owner ma_so_id run function monolith_anim:sequence/internal/$(action)
