# Generated by tools/build-animation-sequence.mjs
tag @s add monolith_anim.sequence
$scoreboard players set @s ma_si_id $(instance)
$scoreboard players set @s ma_so_id $(owner)
data modify entity @s data.sequence set from storage monolith_anim:sequence requests[-1].definition
execute store result score @s ma_sq_end run data get entity @s data.sequence.duration
execute store result score @s ma_sq_pri run data get entity @s data.sequence.priority
scoreboard players set @s ma_sq_time 0
scoreboard players set @s ma_sq_pause 0
scoreboard players set @s ma_sq_block 0
scoreboard players set @s ma_sq_frozen 0
scoreboard players set @s ma_sq_dead 0
scoreboard players set @s ma_sq_live 0
