# Generated by tools/build-animation-sequence.mjs
$execute as @e[tag=monolith_anim.owner,scores={ma_so_id=$(owner)},limit=1] at @s run function monolith_anim:sequence/internal/event_owner with storage monolith_anim:sequence frames[-1]
