# Generated by tools/build-animation-sequence.mjs
data modify storage monolith_anim:sequence frames append value {instance:0,owner:0,time:0,previous_id:0,previous_owner:0,previous_time:0,previous_reason:0,reason:1}
execute store result storage monolith_anim:sequence frames[-1].instance int 1 run scoreboard players get @s ma_si_id
execute store result storage monolith_anim:sequence frames[-1].owner int 1 run scoreboard players get @s ma_so_id
execute store result storage monolith_anim:sequence frames[-1].time int 1 run scoreboard players get @s ma_sq_time
execute store result storage monolith_anim:sequence frames[-1].previous_id int 1 run scoreboard players get #current ma_si_id
execute store result storage monolith_anim:sequence frames[-1].previous_owner int 1 run scoreboard players get #owner ma_so_id
data modify storage monolith_anim:sequence frames[-1].callback set from entity @s data.sequence.on_complete
data modify storage monolith_anim:sequence frames[-1].slot set from entity @s data.sequence.slot
execute as @s run function monolith_anim:sequence/internal/event_dispatch with storage monolith_anim:sequence frames[-1]
function monolith_anim:sequence/internal/restore_context with storage monolith_anim:sequence frames[-1]
data remove storage monolith_anim:sequence frames[-1]
