# Generated by tools/build-animation-sequence.mjs
execute store result storage monolith_anim:sequence frames[-1].previous_time int 1 run scoreboard players get @s ml_seq_time
execute store result storage monolith_anim:sequence frames[-1].previous_reason int 1 run scoreboard players get @s ml_seq_reason
$scoreboard players set #current ma_si_id $(instance)
$scoreboard players set #owner ma_so_id $(owner)
$scoreboard players set @s ml_seq_time $(time)
$scoreboard players set @s ml_seq_reason $(reason)
function monolith_anim:sequence/internal/layer_event with storage monolith_anim:sequence frames[-1]
execute store result score #depth ma_sq_tmp run data get storage monolith_anim:sequence frames
# Bound recursive callback chains. State transitions and cleanup still happen beyond the bound.
$execute if score #depth ma_sq_tmp matches ..16 run function $(callback)
function monolith_anim:sequence/internal/restore_owner with storage monolith_anim:sequence frames[-1]
