# Generated by tools/build-animation-sequence.mjs
tag @s remove monolith_anim.sequence_step
execute if score @s ma_sq_frozen matches 1 run return 0
scoreboard players set @s ma_sq_frozen 1
function monolith_anim:sequence/internal/event_pause
