# Generated by tools/build-animation-sequence.mjs
execute if score @s ml_seq_reason matches 2..3 run function monolith_anim:layer/clear {slot:2}
execute if score @s ml_seq_reason matches 1 run function monolith_anim:layer/resume {slot:2}
scoreboard players set @s ml_sq_slot2 0
