# Generated by tools/build-animation-sequence.mjs
execute if score #next ma_so_id matches 2147483647 run return 0
scoreboard players add #next ma_so_id 1
scoreboard players operation @s ma_so_id = #next ma_so_id
