# Generated by tools/build-animation-sequence.mjs
$execute unless data storage monolith_anim:sequence definitions."$(id)" run return 0
$data modify storage monolith_anim:sequence requests[-1].definition set from storage monolith_anim:sequence definitions."$(id)"
data modify storage monolith_anim:sequence requests[-1].result set value -2
execute store result score #duration ma_sq_tmp run data get storage monolith_anim:sequence requests[-1].definition.duration
execute store result score #priority ma_sq_tmp run data get storage monolith_anim:sequence requests[-1].definition.priority
execute store result score #slot ma_sq_tmp run data get storage monolith_anim:sequence requests[-1].definition.slot
execute unless score #duration ma_sq_tmp matches 0..2000000 run return 0
execute unless score #priority ma_sq_tmp matches -1000000..1000000 run return 0
execute unless score #slot ma_sq_tmp matches -1..3 run return 0
execute unless data storage monolith_anim:sequence requests[-1]{mode:"parallel"} unless data storage monolith_anim:sequence requests[-1]{mode:"wait"} unless data storage monolith_anim:sequence requests[-1]{mode:"pause"} unless data storage monolith_anim:sequence requests[-1]{mode:"cancel"} unless data storage monolith_anim:sequence requests[-1]{mode:"replace"} run return 0
execute if data storage monolith_anim:sequence requests[-1]{api:"child",mode:"pause"} run return 0
execute if data storage monolith_anim:sequence requests[-1]{api:"child",mode:"cancel"} run return 0
execute if data storage monolith_anim:sequence requests[-1]{api:"interrupt",mode:"wait"} run return 0
data modify storage monolith_anim:sequence requests[-1].result set value -3
$execute if data storage monolith_anim:sequence requests[-1]{api:"child"} unless entity @e[type=minecraft:marker,tag=monolith_anim.sequence,scores={ma_si_id=$(parent),ma_so_id=$(owner),ma_sq_live=1,ma_sq_dead=0},limit=1] run return 0
$execute if data storage monolith_anim:sequence requests[-1]{api:"child"} unless score #owner ma_so_id matches $(owner) run return 0
# Whole-owner interrupt arbitration; manually paused and waiting instances retain priority.
scoreboard players set #denied ma_sq_tmp 0
$execute if data storage monolith_anim:sequence requests[-1]{api:"interrupt"} as @e[type=minecraft:marker,tag=monolith_anim.sequence,scores={ma_so_id=$(owner),ma_sq_live=1,ma_sq_dead=0}] if score @s ma_sq_pri > #priority ma_sq_tmp run scoreboard players set #denied ma_sq_tmp 1
execute if score #denied ma_sq_tmp matches 1 run return 0
data modify storage monolith_anim:sequence requests[-1].result set value -4
scoreboard players set #count ma_sq_tmp 0
$execute as @e[type=minecraft:marker,tag=monolith_anim.sequence,scores={ma_so_id=$(owner)}] run scoreboard players add #count ma_sq_tmp 1
execute if score #count ma_sq_tmp matches 64.. run return 0
scoreboard players set #count ma_sq_tmp 0
execute as @e[type=minecraft:marker,tag=monolith_anim.sequence] run scoreboard players add #count ma_sq_tmp 1
execute if score #count ma_sq_tmp matches 256.. run return 0
execute if score #next ma_si_id matches 2147483647 run return 0
data modify storage monolith_anim:sequence requests[-1].result set value -5
function monolith_anim:sequence/internal/check_slot with storage monolith_anim:sequence requests[-1]
execute if score #denied ma_sq_tmp matches 1 run return 0
scoreboard players add #next ma_si_id 1
execute store result storage monolith_anim:sequence requests[-1].instance int 1 run scoreboard players get #next ma_si_id
# Reserve a marker before callbacks; nested starts count pending reservations.
execute at @s summon minecraft:marker run function monolith_anim:sequence/internal/create with storage monolith_anim:sequence requests[-1]
function monolith_anim:sequence/internal/change_existing with storage monolith_anim:sequence requests[-1]
# A callback may have claimed a formerly free slot. Never steal its ownership.
function monolith_anim:sequence/internal/activate with storage monolith_anim:sequence requests[-1]
execute if data storage monolith_anim:sequence requests[-1]{result:-5} run function monolith_anim:sequence/internal/rollback with storage monolith_anim:sequence requests[-1]
