# Generated by tools/build-animation-sequence.mjs
$execute as @e[type=minecraft:marker,tag=monolith_anim.sequence,scores={ma_sq_block=$(instance),ma_sq_dead=0}] run function monolith_anim:sequence/internal/unblock
