# Generated by tools/build-animation-sequence.mjs
$execute as @e[type=minecraft:marker,tag=monolith_anim.sequence,scores={ma_si_id=$(instance)},limit=1] run function monolith_anim:sequence/internal/cancel
