# Generated by tools/build-animation-sequence.mjs
execute unless score @s ma_sq_dead matches 0 run return 0
execute unless score @s ma_sq_pause matches 0 run return 0
execute unless score @s ma_sq_block matches 0 run return 0
execute unless score @s ma_sq_frozen matches 1 run return 0
scoreboard players set @s ma_sq_frozen 0
function monolith_anim:sequence/internal/event_resume
