# Generated by tools/build-animation-sequence.mjs
tag @s remove monolith_anim.sequence_step
execute unless score @s ma_sq_live matches 1 run return 0
execute unless score @s ma_sq_dead matches 0 run return 0
execute unless score @s ma_sq_pause matches 0 run return 0
execute unless score @s ma_sq_block matches 0 run return 0
execute if score @s ma_sq_time > @s ma_sq_end run return run function monolith_anim:sequence/internal/complete
# Capture visible time, then consume this event before dispatch. wait never replays an event.
data modify entity @s data.sequence.event_time set value 0
execute store result entity @s data.sequence.event_time int 1 run scoreboard players get @s ma_sq_time
scoreboard players add @s ma_sq_time 1
function monolith_anim:sequence/internal/event_tick
execute unless entity @s run return 0
execute if score @s ma_sq_live matches 1 if score @s ma_sq_dead matches 0 if score @s ma_sq_pause matches 0 if score @s ma_sq_block matches 0 if score @s ma_sq_time > @s ma_sq_end run function monolith_anim:sequence/internal/complete
