# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l3sza 1
scoreboard players set @s ml_l3szt 0
scoreboard players operation @s ml_l3szd = @s ml_lc_d
scoreboard players operation @s ml_l3sze = @s ml_le_easing
scoreboard players operation @s ml_l3szf = @s ml_lc_f
scoreboard players operation @s ml_l3szz = @s ml_lc_z
scoreboard players operation @s ml_l3szv = @s ml_lc_f
execute if score @s ml_l3szd matches 0 run function monolith_anim:layer/slot/3/sz/finish
function monolith_anim:layer/slot/3/refresh
