# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players operation @s ml_l0syv = @s ml_l0syz
scoreboard players set @s ml_l0sya 0
function monolith_anim:layer/slot/0/refresh
