# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l0sya 1
scoreboard players set @s ml_l0syt 0
scoreboard players operation @s ml_l0syd = @s ml_lc_d
scoreboard players operation @s ml_l0sye = @s ml_le_easing
scoreboard players operation @s ml_l0syf = @s ml_lc_f
scoreboard players operation @s ml_l0syz = @s ml_lc_z
scoreboard players operation @s ml_l0syv = @s ml_lc_f
execute if score @s ml_l0syd matches 0 run function monolith_anim:layer/slot/0/sy/finish
function monolith_anim:layer/slot/0/refresh
