# Generated by tools/build-animation-sequence.mjs
execute unless entity @s run return 0
execute unless score @s ma_so_id = #owner ma_so_id run return 0
execute unless data storage monolith_anim:sequence frames[-1] run return 0
function monolith_anim:sequence/internal/current_complete with storage monolith_anim:sequence frames[-1]
