# Generated by tools/build-animation-sequence.mjs
execute unless entity @s run return 0
execute unless entity @s[tag=monolith_anim.owner] run return 0
execute unless score @s ma_so_id matches 1.. run return 0
scoreboard players operation #control_owner ma_so_id = @s ma_so_id
$data modify storage monolith_anim:sequence control set value {instance:$(instance),action:"$(action)"}
execute if data storage monolith_anim:sequence control{action:"complete"} run function monolith_anim:sequence/internal/control with storage monolith_anim:sequence control
execute if data storage monolith_anim:sequence control{action:"cancel"} run function monolith_anim:sequence/internal/control with storage monolith_anim:sequence control
execute if data storage monolith_anim:sequence control{action:"pause"} run function monolith_anim:sequence/internal/control with storage monolith_anim:sequence control
execute if data storage monolith_anim:sequence control{action:"resume"} run function monolith_anim:sequence/internal/control with storage monolith_anim:sequence control
