# Generated by tools/build-animation-sequence.mjs
$data modify storage monolith_anim:sequence definitions."$(id)" set value {tick:"monolith_anim:sequence/noop",duration:0,priority:0,slot:-1,on_complete:"monolith_anim:sequence/noop",on_cancel:"monolith_anim:sequence/noop",on_pause:"monolith_anim:sequence/noop",on_resume:"monolith_anim:sequence/noop"}
$data modify storage monolith_anim:sequence definitions."$(id)" merge value $(definition)
