# Generated by tools/build-animation-sequence.mjs
execute unless entity @s run return 0
scoreboard players set @s ml_seq_result -1
execute store result score #depth ma_sq_tmp run data get storage monolith_anim:sequence requests
execute if score #depth ma_sq_tmp matches 16.. run return 0
function monolith_anim:sequence/owner
execute unless score @s ma_so_id matches 1.. run return 0
# An owner interrupt is an atomic transaction. Callbacks may start children, but cannot nest another interrupt before commit.
execute store result storage monolith_anim:sequence interrupt_guard.owner int 1 run scoreboard players get @s ma_so_id
function monolith_anim:sequence/internal/interrupt_available with storage monolith_anim:sequence interrupt_guard
execute if score @s ml_seq_result matches -6 run return -6
$data modify storage monolith_anim:sequence requests append value {id:"$(id)",api:"interrupt",mode:"$(mode)",result:-1,parent:0}
execute store result storage monolith_anim:sequence requests[-1].owner int 1 run scoreboard players get @s ma_so_id
function monolith_anim:sequence/internal/prepare with storage monolith_anim:sequence requests[-1]
execute store result score @s ml_seq_result run data get storage monolith_anim:sequence requests[-1].result
data remove storage monolith_anim:sequence requests[-1]
return run scoreboard players get @s ml_seq_result
