# Generated by tools/build-animation-sequence.mjs
scoreboard objectives add ma_si_id dummy
scoreboard objectives add ma_so_id dummy
scoreboard objectives add ma_sq_time dummy
scoreboard objectives add ma_sq_end dummy
scoreboard objectives add ma_sq_pri dummy
scoreboard objectives add ma_sq_pause dummy
scoreboard objectives add ma_sq_block dummy
scoreboard objectives add ma_sq_frozen dummy
scoreboard objectives add ma_sq_dead dummy
scoreboard objectives add ma_sq_live dummy
scoreboard objectives add ma_sq_tmp dummy
scoreboard objectives add ml_seq_time dummy
scoreboard objectives add ml_seq_result dummy
scoreboard objectives add ml_seq_reason dummy
scoreboard objectives add ml_sq_slot0 dummy
scoreboard objectives add ml_sq_slot1 dummy
scoreboard objectives add ml_sq_slot2 dummy
scoreboard objectives add ml_sq_slot3 dummy
scoreboard players add #next ma_si_id 0
scoreboard players add #next ma_so_id 0
scoreboard players set #current ma_si_id 0
scoreboard players set #owner ma_so_id 0
data modify storage monolith_anim:sequence frames set value []
data modify storage monolith_anim:sequence requests set value []
data modify storage monolith_anim:sequence cleanup_frames set value []
execute unless data storage monolith_anim:sequence definitions run data modify storage monolith_anim:sequence definitions set value {}
# Existing markers, clocks, blockers, definitions and monotonically allocated IDs survive /reload.
