# Generated by tools/build-animation-sequence.mjs
execute unless entity @s run return 0
execute unless score @s ma_so_id matches 1.. run function monolith_anim:sequence/internal/owner_allocate
tag @s add monolith_anim.owner
scoreboard players add @s ml_sq_slot0 0
scoreboard players add @s ml_sq_slot1 0
scoreboard players add @s ml_sq_slot2 0
scoreboard players add @s ml_sq_slot3 0
function monolith_anim:sequence/internal/check_claim_0
function monolith_anim:sequence/internal/check_claim_1
function monolith_anim:sequence/internal/check_claim_2
function monolith_anim:sequence/internal/check_claim_3
