# Generated by tools/build-animation-sequence.mjs
# Snapshot excludes starts and resumes made during this tick, independent of selector order.
tag @e[type=minecraft:marker,tag=monolith_anim.sequence] remove monolith_anim.sequence_step
tag @e[type=minecraft:marker,tag=monolith_anim.sequence,scores={ma_sq_live=1,ma_sq_dead=0,ma_sq_pause=0,ma_sq_block=0}] add monolith_anim.sequence_step
execute as @e[type=minecraft:marker,tag=monolith_anim.sequence] run function monolith_anim:sequence/internal/check_owner
execute as @e[type=minecraft:marker,tag=monolith_anim.sequence_step] at @s run function monolith_anim:sequence/internal/tick
