# Generated by tools/build-animation-debug.mjs
# Layer 2 has its own shake while instance-owned layers 0/1 are paused.
execute if score @s ml_seq_time matches 0 run function monolith_anim:layer/start {slot:2,property:"translation_x",from:0,to:350,duration:4,easing:"out_quad"}
execute if score @s ml_seq_time matches 4 run function monolith_anim:layer/start {slot:2,property:"translation_x",from:350,to:-350,duration:4,easing:"linear"}
execute if score @s ml_seq_time matches 8 run function monolith_anim:layer/start {slot:2,property:"translation_x",from:-350,to:250,duration:4,easing:"linear"}
execute if score @s ml_seq_time matches 12 run function monolith_anim:layer/start {slot:2,property:"translation_x",from:250,to:-150,duration:4,easing:"linear"}
execute if score @s ml_seq_time matches 16 run function monolith_anim:layer/start {slot:2,property:"translation_x",from:-150,to:0,duration:4,easing:"out_quad"}
execute if score @s ml_seq_time matches 0 run particle minecraft:crit ~ ~1 ~ 0.2 0.2 0.2 0.1 12 force
execute if score @s ml_seq_time matches 0 run playsound minecraft:block.amethyst_block.hit master @a[distance=..32] ~ ~ ~ 0.6 0.8
