# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l2sxa 1
scoreboard players set @s ml_l2sxt 0
scoreboard players operation @s ml_l2sxd = @s ml_lc_d
scoreboard players operation @s ml_l2sxe = @s ml_le_easing
scoreboard players operation @s ml_l2sxf = @s ml_lc_f
scoreboard players operation @s ml_l2sxz = @s ml_lc_z
scoreboard players operation @s ml_l2sxv = @s ml_lc_f
execute if score @s ml_l2sxd matches 0 run function monolith_anim:layer/slot/2/sx/finish
function monolith_anim:layer/slot/2/refresh
