# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players operation @s ml_l1rxv = @s ml_l1rxz
scoreboard players set @s ml_l1rxa 0
function monolith_anim:layer/slot/1/refresh
