# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players set @s ml_l1rxa 1
scoreboard players set @s ml_l1rxt 0
scoreboard players operation @s ml_l1rxd = @s ml_lc_d
scoreboard players operation @s ml_l1rxe = @s ml_le_easing
scoreboard players operation @s ml_l1rxf = @s ml_lc_f
scoreboard players operation @s ml_l1rxz = @s ml_lc_z
scoreboard players operation @s ml_l1rxv = @s ml_lc_f
execute if score @s ml_l1rxd matches 0 run function monolith_anim:layer/slot/1/rx/finish
function monolith_anim:layer/slot/1/refresh
