# Generated by tools/build-animation-layers.mjs
scoreboard players set @s ml_l_dirty 1
scoreboard players add @s ml_l1rxt 1
execute if score @s ml_l1rxt >= @s ml_l1rxd run return run function monolith_anim:layer/slot/1/rx/finish
scoreboard players operation @s ml_le_tmp0 = @s ml_l1rxt
scoreboard players operation @s ml_le_tmp0 *= #scale ml_le_tmp0
scoreboard players operation @s ml_le_tmp0 /= @s ml_l1rxd
scoreboard players operation @s ml_le_easing = @s ml_l1rxe
function monolith_anim:easing/dispatch
scoreboard players operation @s ml_lm_u = @s ml_le_tmp1
scoreboard players operation @s ml_lm_a = @s ml_l1rxf
scoreboard players operation @s ml_lm_b = @s ml_l1rxz
function monolith_anim:math/layer_lerp
scoreboard players operation @s ml_l1rxv = @s ml_lm_v
