# Generated by tools/build-animation-layers.mjs
execute store result storage monolith_anim:easing_runtime index int 1 run scoreboard players get @s ml_le_lut_i
function monolith_anim:easing/lut/read/out_circ with storage monolith_anim:easing_runtime
scoreboard players operation @s ml_le_lut_b = @s ml_le_lut_a
scoreboard players add @s ml_le_lut_i 1
execute store result storage monolith_anim:easing_runtime index int 1 run scoreboard players get @s ml_le_lut_i
function monolith_anim:easing/lut/read/out_circ with storage monolith_anim:easing_runtime
function monolith_anim:easing/lut/interpolate
